-- Claude (dev-owner) 2026-10-03, DH start audit: player choice texts in Russian where an enUS locale row exists (the server does not read enUS locale rows). Fel Secrets choice 231 buttons showed Истребление/Месть. Apply with --default-character-set=utf8mb4.
UPDATE world.playerchoice_response SET `Answer`='Havoc' WHERE ChoiceId=231 AND ResponseId=478;
UPDATE world.playerchoice_response SET `Answer`='Vengeance' WHERE ChoiceId=231 AND ResponseId=479;
UPDATE world.playerchoice_response SET `Header`='Assassination' WHERE ChoiceId=262 AND ResponseId=568;
UPDATE world.playerchoice_response SET `Answer`='Select' WHERE ChoiceId=262 AND ResponseId=568;
UPDATE world.playerchoice_response SET `Description`='The Kingslayers were Garona\'s daggers as Gul\'dan\'s personal assassin. They inflict a traceless poison, leaving little evidence of their grim work.\n\nGarona stowed the blades away long ago in her anguish, but she has taken them up once more against a dangerous Legion cult.\n\nWe have to find her.' WHERE ChoiceId=262 AND ResponseId=568;
UPDATE world.playerchoice_response SET `Header`='Outlaw' WHERE ChoiceId=262 AND ResponseId=569;
UPDATE world.playerchoice_response SET `Answer`='Select' WHERE ChoiceId=262 AND ResponseId=569;
UPDATE world.playerchoice_response SET `Description`='The Dread Admiral Eliza is known as the scourge of the South Seas. Many have learned to fear her cursed blades.\n\nWe\'ve tracked her anchored off the coast of Azsuna in the Broken Isles. Her blades can be yours if you hurry.' WHERE ChoiceId=262 AND ResponseId=569;
UPDATE world.playerchoice_response SET `Header`='Subtlety' WHERE ChoiceId=262 AND ResponseId=570;
UPDATE world.playerchoice_response SET `Answer`='Select' WHERE ChoiceId=262 AND ResponseId=570;
UPDATE world.playerchoice_response SET `Description`='The Legion now boast one Akaari Shadowgore - an eredar assassin unlike any we\'ve seen. Her daggers twist the very air around their wielder to conceal them in shadow.\n\nWe have intelligence pointing to her current location. Now is the time to strike.' WHERE ChoiceId=262 AND ResponseId=570;
UPDATE world.playerchoice_response SET `Header`='Light\'s Judgment' WHERE ChoiceId=317 AND ResponseId=771;
UPDATE world.playerchoice_response SET `Answer`='Select' WHERE ChoiceId=317 AND ResponseId=771;
UPDATE world.playerchoice_response SET `Description`='Selecting this allows you to target and fire Light\'s Judgment, the Vindicaar\'s main weapon, while on Argus.' WHERE ChoiceId=317 AND ResponseId=771;
UPDATE world.playerchoice_response SET `Header`='Fel Heart' WHERE ChoiceId=317 AND ResponseId=775;
UPDATE world.playerchoice_response SET `Answer`='Select' WHERE ChoiceId=317 AND ResponseId=775;
UPDATE world.playerchoice_response SET `Description`='Selecting the Fel Heart of Argus allows you, when on Argus, to be brought back to life after taking fatal damage and continually heals you while not in combat.' WHERE ChoiceId=317 AND ResponseId=775;
UPDATE world.playerchoice_response SET `Answer`='Activate' WHERE ChoiceId=317 AND ResponseId=782;
UPDATE world.playerchoice_response SET `Description`='Activate the Matrix Core and select Light\'s Judgment, the Vindicaar\'s main weapon, as your power on Argus.' WHERE ChoiceId=317 AND ResponseId=782;
UPDATE world.playerchoice SET Question='What outpost structure should we construct?' WHERE ChoiceId=52;
UPDATE world.playerchoice SET Question='What outpost structure should we construct?' WHERE ChoiceId=53;
UPDATE world.playerchoice SET Question='What outpost structure should we construct?' WHERE ChoiceId=54;
UPDATE world.playerchoice SET Question='What outpost structure should we construct?' WHERE ChoiceId=56;
UPDATE world.playerchoice SET Question='What outpost structure should we construct?' WHERE ChoiceId=57;
UPDATE world.playerchoice SET Question='Strategic Assault Choice' WHERE ChoiceId=70;
UPDATE world.playerchoice SET Question='Strategic Assault Choice' WHERE ChoiceId=128;
UPDATE world.playerchoice SET Question='Strategic Assault Choice' WHERE ChoiceId=174;
UPDATE world.playerchoice SET Question='Which weapon should we pursue first?' WHERE ChoiceId=262;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=270;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=273;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=274;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=275;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=277;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=279;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=280;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=282;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=284;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=287;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=288;
UPDATE world.playerchoice SET Question='Do you wish to pursue a second artifact weapon?' WHERE ChoiceId=292;
UPDATE world.playerchoice SET Question='Select a Vindicaar power for use on Argus.' WHERE ChoiceId=317;
