-- #155 (c) (help-helper, Claude 2026-10-02): quests 38925, 39294, 39522 (Ashran Dominance) and 40312 (A Timely Opportunity)
-- had Russian base text (VerifiedBuild 21154; the upstream dump has the same). English clients see the base text wherever
-- quest_template_locale has no enUS value. Sources: title / objective / description from the enUS quest_template_locale
-- rows of 38925 and 39522 and from Wowhead (39294, 40312; Wowhead spells the dungeon "Neltharian's Vault").
-- QuestCompletionLog has no English source anywhere (no enUS value, not on Wowhead): translated from the Russian
-- ("Return to Chris Clarkie ...", "Speak with Wrathion ..."). AreaDescription is empty in all four.
-- Apply with --default-character-set=utf8mb4. Undo: undo_quest_titles_ru_155.sql
SET NAMES utf8mb4;
UPDATE world.quest_template SET LogTitle = 'Ashran Dominance', LogDescription = 'Defeat the enemy faction at the event locations in Ashran and slay their leader within their base.', QuestDescription = 'As we feared the Horde are trying to consolidate their position here on the island by looting it, just like we feared. Get out there and show them the Alliance won''t put up with their aggression.', QuestCompletionLog = 'Return to Chris Clarkie at the Alliance base in Ashran.' WHERE ID = 38925 AND LogTitle = 'Доминирование в Ашране';
UPDATE world.quest_template SET LogTitle = 'Ashran Dominance', LogDescription = 'Defeat the Horde at all event locations in Ashran and kill High Warlord Volrath.', QuestDescription = 'As we feared the Horde are trying to consolidate their position here on the island by looting it, just like we feared. Get out there and show them the Alliance won''t put up with their aggression.', QuestCompletionLog = 'Return to Chris Clarkie at the Alliance base in Ashran.' WHERE ID = 39294 AND LogTitle = 'Доминирование в Ашране';
UPDATE world.quest_template SET LogTitle = 'Ashran Dominance', LogDescription = 'Defeat the Horde at the event locations in Ashran and kill High Warlord Volrath.', QuestDescription = 'As we feared the Horde are trying to consolidate their position here on the island by looting it, just like we feared. Get out there and show them the Alliance won''t put up with their aggression.', QuestCompletionLog = 'Return to Chris Clarkie at the Alliance base in Ashran.' WHERE ID = 39522 AND LogTitle = 'Доминирование в Ашране';
UPDATE world.quest_template SET LogTitle = 'A Timely Opportunity', LogDescription = 'Assist Spiritwalker Ebonhorn in Neltharian''s Vault.', QuestDescription = 'Now that the whole "spirit journey" thing is out of the way we can get down to business.', QuestCompletionLog = 'Speak with Wrathion in Neltharian''s Vault.' WHERE ID = 40312 AND LogTitle = 'Своевременная возможность';
