-- #155 (help-helper, Claude 2026-10-02): 16 quests whose quest_template base text is Russian and that have no enUS
-- quest_template_locale row, so English clients saw Russian. Also the objective line of 41289 and the request text of 90005.
-- Sources: Wowhead titles for 37972, 41289, 41334, 41507, 41547, 47040 (41289's objective = its item 140947 "Flourishing
-- Aethril"). 41325 and 41577 are no longer on Wowhead: 41325 = its objective item 134809 "Slick Seal Hide" (Wowhead also
-- lists the twin quest 41583 "Slick Seal Hide"); 41577 "Roc Talon Scale" is a translation of the Russian title (its
-- objective item is 134131 Bristled Bear Skin, so the row itself looks mismatched). The other columns of the world quests
-- are empty (47040: NULL).
-- 90000-90007 are custom New Year quests (not retail, no English source): all their text is TRANSLATED from the Russian,
-- including 90005's quest_request_items CompletionText. Place/item names use the English game names (Shadowmoon Valley,
-- Winterspring, Keeper Remulos, Swamp of Sorrows, Khorium Scope, Gadgetzan, Auchindoun, Howling Fjord); the custom names are
-- transliterated (Albond, Parneti, Kaltas, Dionis, Shakro, "Thornwood Stone").
-- Guards: the exact Russian LogTitle / objective / request text, so a second run or a changed row does nothing.
-- Apply with --default-character-set=utf8mb4. Undo: undo_quest_texts_ru_18.sql
SET NAMES utf8mb4;
UPDATE world.quest_template SET LogTitle = 'Pet Battles Not Active' WHERE ID = 37972 AND LogTitle = 'Неактивные битвы питомцев';
UPDATE world.quest_template SET LogTitle = 'Flourishing Aethril' WHERE ID = 41289 AND LogTitle = 'Цветущий айтрил';
UPDATE world.quest_template SET LogTitle = 'Slick Seal Hide' WHERE ID = 41325 AND LogTitle = 'Скользкая шкура тюленя';
UPDATE world.quest_template SET LogTitle = 'Musky Bear Hide' WHERE ID = 41334 AND LogTitle = 'Пахнущая мускусом медвежья шкура';
UPDATE world.quest_template SET LogTitle = 'Leystone Basilisks' WHERE ID = 41507 AND LogTitle = 'Василиски силового камня';
UPDATE world.quest_template SET LogTitle = 'Fjarnskaggl Cluster' WHERE ID = 41547 AND LogTitle = 'Пучок фьярнскаггла';
UPDATE world.quest_template SET LogTitle = 'Roc Talon Scale' WHERE ID = 41577 AND LogTitle = 'Чешуйка с лапы руха';
UPDATE world.quest_template SET LogTitle = 'Fate Sealed' WHERE ID = 47040 AND LogTitle = 'Печать судьбы';
UPDATE world.quest_template SET LogTitle = 'There Will Be No Holiday!', LogDescription = 'Find Albond in Shadowmoon Valley.', QuestDescription = 'A terrible misfortune has befallen our lands. The New Year has been stolen! And no one knows how this will affect the fate of all Azeroth!\n$c, if you are $gwilling:willing; to help us, and to help all of Azeroth, you will have to find out who stole the holiday.\n\nRumor has it that a mage named Albond is in Shadowmoon Valley, in Outland.\nAlbond is a descendant of the great alchemist Parneti, who created the New Year several thousand years ago. I think he will help us.\n\nBe careful with him. I have heard he is a little strange.', AreaDescription = 'Albond found' WHERE ID = 90000 AND LogTitle = 'Праздника не будет!';
UPDATE world.quest_template SET LogTitle = 'The Story of the New Year', LogDescription = 'Listen to Albond''s story.', QuestDescription = 'Aha, you again. I knew Greatfather Winter''s helpers would send someone to me, for I am the only one who might know anything about this.\nShall I tell you a thing or two?', AreaDescription = 'Listen to the old mage''s story' WHERE ID = 90001 AND LogTitle = 'История Нового года';
UPDATE world.quest_template SET LogTitle = 'Materials', LogDescription = 'Bring Albond the ingredients.', QuestDescription = 'Building the device will take a few ingredients.\nThe heart of a Nexus dragon whelp from the Borean Tundra, 6 handfuls of first snow from Winterspring, and some magical water from Lake Elune''ara. You can get the water if you ask Keeper Remulos nicely.', AreaDescription = 'Return to Albond with the ingredients.' WHERE ID = 90002 AND LogTitle = 'Материалы';
UPDATE world.quest_template SET LogTitle = 'The Forgotten Part', LogDescription = 'Find the goblin Kaltas and get the Thornwood Stone from him.', QuestDescription = 'Oh, my memory is not what it used to be. I forgot one more part for our wondrous device. The Thornwood Stone!\n\nThere is a goblin who hangs around the Swamp of Sorrows. He has what we need... the Thornwood Stone, which holds ancient magic. We cannot do without it. The goblin is called Kaltas. I think you will find him quickly.', QuestCompletionLog = 'Return to Albond' WHERE ID = 90003 AND LogTitle = 'Забытая деталь';
UPDATE world.quest_template SET LogTitle = 'Even Criminals Have Holidays', LogDescription = 'Bring the goblin the things he needs.', QuestDescription = 'The Thornwood Stone, you say? Yes, I have it, but I''m not just going to hand it over.\n\nI''ve been wanting to try Ice Cold Milk and Gingerbread Cookies for ages, but I have no time at all right now. I''m running around like a squirrel in a wheel all day with these contract killings and other dirty business.\n\nBy the way, the scope on my rifle broke the other day, and what''s an assassin without his optics? I hear the Khorium Scope is an excellent model, so you''ll have to find me that too, and then I''ll give you the stone.', QuestCompletionLog = 'Return to Kaltas' WHERE ID = 90004 AND LogTitle = 'И у преступников бывает праздник';
UPDATE world.quest_template SET LogTitle = 'Energy Surge Detected!', LogDescription = 'Go to Gadgetzan and question the innkeeper.', QuestDescription = 'The compass lit up the sky with a blue glow. The image was very sharp, as if painted. I see a pier, houses, a tavern. That is none other than Gadgetzan. We must go there and question the locals. I think the innkeeper should know something.', AreaDescription = 'Innkeeper questioned', QuestCompletionLog = 'Speak with Dionis' WHERE ID = 90005 AND LogTitle = 'Всплеск энергии обнаружен!';
UPDATE world.quest_template SET LogTitle = 'In Search of Shakro', LogDescription = 'Shakro is somewhere in Auchindoun. Find him!', QuestDescription = 'The one you are looking for came by yesterday. His name is Shakro. He deals with imps or demons, I don''t know exactly. He wanted me to help him find mercenaries... said he was in some kind of danger. Of course I refused him, I gave up all that dirty business long ago.\nHe left me a hint on how to find him. He said he would be somewhere in Auchindoun, but he would not say where exactly.', QuestCompletionLog = 'Take the letter to Albond' WHERE ID = 90006 AND LogTitle = 'На поиски Шакро';
UPDATE world.quest_template SET LogTitle = 'Saving the New Year', LogDescription = 'Go to the Howling Fjord and save the New Year!', QuestDescription = 'Very strange. The letter says that "Winter" has been ordered to destroy the artifact, because the demons of this world were not strong enough to destroy it themselves.\nBut how can that be? Has "Winter" betrayed the spirit of the New Year? Something is wrong here. Perhaps his mind has been seized by the enemy?\n\nThe artifact can only be destroyed in the place where it was made. In the mountains of the Howling Fjord! Let us hurry!', AreaDescription = 'New Year saved', QuestCompletionLog = 'Receive your gift' WHERE ID = 90007 AND LogTitle = 'Спасение нового года';
UPDATE world.quest_objectives SET Description = 'Flourishing Aethril' WHERE ID = 282167 AND QuestID = 41289 AND Description = 'Цветущий айтрил';
UPDATE world.quest_request_items SET CompletionText = 'This compass once belonged to my great-grandfather. I think it is only fair that you give it to me, and I will tell you what you want to know.' WHERE ID = 90005 AND CompletionText = 'Этот компас когда-то принадлежал моему прадеду, я думаю будет справедливо, если ты отдашь его мне, а  я расскажу тебе то, что тебя интересует.';
