-- Gear-Up NPC (500010, script npc_gear_up), owner request 2026-09-28 (Claude): staff only (GM accounts).
-- Bags (4x Imbued Silkweave Bag), best-in-slot gear per spec of your class, max professions.
-- Spawn it in game with: .npc add 500010
-- The gear sets are in gear_npc_items.sql (generated by tools/fill_character/fill_character.py export).
-- Undo: undo_gear_up_npc.sql
DELETE FROM world.creature_template WHERE entry = 500010;
INSERT INTO world.creature_template (entry, gossip_menu_id, minlevel, maxlevel, HealthScalingExpansion, exp, faction, npcflag, speed_walk, speed_run, scale,
    dmg_multiplier, baseattacktime, rangeattacktime, unit_class, unit_flags, unit_flags2, RegenHealth, mechanic_immune_mask, WorldEffects, PassiveSpells, ScriptName)
VALUES (500010, 0, 110, 110, 6, 6, 35, 1, 1, 1.14286, 1, 1, 2000, 2000, 1, 2, 2048, 1, 0, '', '', 'npc_gear_up');

DELETE FROM world.creature_template_wdb WHERE Entry = 500010;
INSERT INTO world.creature_template_wdb (Entry, Name1, Title, TypeFlags, Type, Classification, Displayid1, HpMulti, PowerMulti, RequiredExpansion, VerifiedBuild)
VALUES (500010, 'Gear Master', 'Staff Gear-Up', 0, 7, 0, 71904, 1, 1, 0, 26972);
