-- Russian creature names/subtitles -> English (gabrielf03d: Netherlight Temple NPC next to Challenger's Bounty,
-- 400010 "Послушник Храма света Пустоты <Путеводитель по заданиям оплота>"). Undo: undo_russian_creature_names.sql
-- Sweep: every creature_template_wdb row with Cyrillic in Name1..4 / NameAlt1..4 / Title / TitleAlt / CursorName
-- (834 rows; only Name1 834, NameAlt1 61, Title 63, TitleAlt 13 had any). Only the Cyrillic fields change.
-- English source, in this order: the 7.3.5 client's Creature.db2 enUS (122), the enUS rows of
-- creature_template_wdb_locale (586, retail names), else translated by hand (126 custom / unused alpha NPCs).
-- A Russian NameAlt1/TitleAlt (female form) becomes '' like the enUS client data (English has no female form).
-- The enUS locale rows already overrode Name1 in the creature query for 708 of these, but GetName() (e.g. chat
-- sender names) and every other field/row still used the Russian base value.
-- Loaded at startup (LoadWDBCreatureTemplates): live after a worldserver restart. Players who met these NPCs keep
-- the Russian name in their client cache (creaturecache.wdb) until they delete the Cache folder.
-- creature_text (#92) and gameobject_template names are not touched here.
SET NAMES utf8mb4;

-- English from the 7.3.5 client (Creature.db2 enUS)
UPDATE world.creature_template_wdb SET Name1 = 'Crimson Whelpling' WHERE Entry = 7544;
UPDATE world.creature_template_wdb SET Name1 = 'Yu''la, Broodling of Yu''lon' WHERE Entry = 72463;
UPDATE world.creature_template_wdb SET Name1 = 'Sister of Temptation' WHERE Entry = 90206;
UPDATE world.creature_template_wdb SET Name1 = 'Hillstalker Worg' WHERE Entry = 91423;
UPDATE world.creature_template_wdb SET Name1 = 'Bristlemaul' WHERE Entry = 97449;
UPDATE world.creature_template_wdb SET Name1 = 'Forest Critter' WHERE Entry = 110002;
UPDATE world.creature_template_wdb SET Name1 = 'Myonix', Title = 'Manasaber Matron' WHERE Entry = 110340;
UPDATE world.creature_template_wdb SET Name1 = 'Undead Steward' WHERE Entry = 115278;
UPDATE world.creature_template_wdb SET Name1 = 'Snowfeather Hatchling' WHERE Entry = 115784;
UPDATE world.creature_template_wdb SET Name1 = 'Gnoll' WHERE Entry = 116355;
UPDATE world.creature_template_wdb SET Name1 = 'Hiss', Title = 'Lord Serpentis'' Companion' WHERE Entry = 116793;
UPDATE world.creature_template_wdb SET Name1 = 'Tirisgarde Apprentice' WHERE Entry = 119060;
UPDATE world.creature_template_wdb SET Name1 = 'Greywatch Mauler' WHERE Entry = 119061;
UPDATE world.creature_template_wdb SET Name1 = 'Dreamgrove Protector' WHERE Entry = 119077;
UPDATE world.creature_template_wdb SET Name1 = 'Dreamgrove Protector' WHERE Entry = 119078;
UPDATE world.creature_template_wdb SET Name1 = 'Nightborne Huntress' WHERE Entry = 119081;
UPDATE world.creature_template_wdb SET Name1 = 'Nightborne Huntress' WHERE Entry = 119082;
UPDATE world.creature_template_wdb SET Name1 = 'Chieftain Hatuun' WHERE Entry = 119388;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Infernal' WHERE Entry = 119395;
UPDATE world.creature_template_wdb SET Name1 = 'Scorchwing Felspitter' WHERE Entry = 119398;
UPDATE world.creature_template_wdb SET Name1 = 'Vilefiend' WHERE Entry = 119602;
UPDATE world.creature_template_wdb SET Name1 = 'Argussian Vigilant' WHERE Entry = 119828;
UPDATE world.creature_template_wdb SET Name1 = 'Illidan Stormrage' WHERE Entry = 120218;
UPDATE world.creature_template_wdb SET Name1 = 'Prophet Velen' WHERE Entry = 120223;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Ridgestalker' WHERE Entry = 120476;
UPDATE world.creature_template_wdb SET Name1 = 'High Exarch Turalyon' WHERE Entry = 120514;
UPDATE world.creature_template_wdb SET Name1 = 'Chieftain Hatuun' WHERE Entry = 120521;
UPDATE world.creature_template_wdb SET Name1 = 'Prophet Velen' WHERE Entry = 120533;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Ship' WHERE Entry = 120596;
UPDATE world.creature_template_wdb SET Name1 = 'Burning Fiend' WHERE Entry = 120637;
UPDATE world.creature_template_wdb SET Name1 = 'Annihilan Warden' WHERE Entry = 120704;
UPDATE world.creature_template_wdb SET Name1 = 'Annihilan Fanatic' WHERE Entry = 120723;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Seer' WHERE Entry = 120737;
UPDATE world.creature_template_wdb SET Name1 = 'Wounded Captive', NameAlt1 = '' WHERE Entry = 120754;
UPDATE world.creature_template_wdb SET Name1 = 'Arator the Redeemer' WHERE Entry = 120845;
UPDATE world.creature_template_wdb SET Name1 = 'Alleria Windrunner' WHERE Entry = 120917;
UPDATE world.creature_template_wdb SET Name1 = 'Vereesa Windrunner', Title = 'Ranger-General of the Silver Covenant' WHERE Entry = 121179;
UPDATE world.creature_template_wdb SET Name1 = 'Shadow-Touched Krokul' WHERE Entry = 121250;
UPDATE world.creature_template_wdb SET Name1 = 'Lothraxion', Title = 'High Commander' WHERE Entry = 121261;
UPDATE world.creature_template_wdb SET Name1 = 'Grand Artificer Romuul' WHERE Entry = 121263;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Stalker' WHERE Entry = 121295;
UPDATE world.creature_template_wdb SET Name1 = 'Prophet Velen' WHERE Entry = 121345;
UPDATE world.creature_template_wdb SET Name1 = 'Ebon Death Knight' WHERE Entry = 121409;
UPDATE world.creature_template_wdb SET Name1 = 'Thunder Warrior' WHERE Entry = 121412;
UPDATE world.creature_template_wdb SET Name1 = 'Legionfall Defender' WHERE Entry = 121413;
UPDATE world.creature_template_wdb SET Name1 = 'Darklost Krokul' WHERE Entry = 121563;
UPDATE world.creature_template_wdb SET Name1 = 'Vereesa Windrunner', Title = 'Ranger-General of the Silver Covenant' WHERE Entry = 121786;
UPDATE world.creature_template_wdb SET Name1 = 'Panthara Shadowfang' WHERE Entry = 122010;
UPDATE world.creature_template_wdb SET Name1 = 'Ebon Death Knight' WHERE Entry = 122150;
UPDATE world.creature_template_wdb SET Name1 = 'Argus Volcano' WHERE Entry = 122219;
UPDATE world.creature_template_wdb SET Name1 = 'Frenzied Plaguewing' WHERE Entry = 122833;
UPDATE world.creature_template_wdb SET Name1 = 'Commander Vecaya' WHERE Entry = 122911;
UPDATE world.creature_template_wdb SET Name1 = 'Commander Sathrenael' WHERE Entry = 122912;
UPDATE world.creature_template_wdb SET Name1 = 'Mistress Il''thendra' WHERE Entry = 122947;
UPDATE world.creature_template_wdb SET Name1 = 'Gar''zoth' WHERE Entry = 122999;
UPDATE world.creature_template_wdb SET Name1 = 'Seething Harbinger', NameAlt1 = '' WHERE Entry = 123109;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowbound Defiler', NameAlt1 = '' WHERE Entry = 123110;
UPDATE world.creature_template_wdb SET Name1 = 'Shadow-Touched Krokul' WHERE Entry = 123301;
UPDATE world.creature_template_wdb SET Name1 = 'Augari Consul', NameAlt1 = '' WHERE Entry = 123474;
UPDATE world.creature_template_wdb SET Name1 = 'Conservatory Vigilant' WHERE Entry = 123488;
UPDATE world.creature_template_wdb SET Name1 = 'Augari Wakener', NameAlt1 = '' WHERE Entry = 123504;
UPDATE world.creature_template_wdb SET Name1 = 'Void Image' WHERE Entry = 123889;
UPDATE world.creature_template_wdb SET Name1 = 'High Exarch Turalyon' WHERE Entry = 124312;
UPDATE world.creature_template_wdb SET Name1 = 'Magni Bronzebeard', Title = 'The Speaker' WHERE Entry = 124595;
UPDATE world.creature_template_wdb SET Name1 = 'Commander Endaxis' WHERE Entry = 124775;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Ridgestalker' WHERE Entry = 124931;
UPDATE world.creature_template_wdb SET Name1 = 'Image of Grand Artificer Romuul' WHERE Entry = 124975;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Seer' WHERE Entry = 125057;
UPDATE world.creature_template_wdb SET Name1 = 'Blazing Felshard' WHERE Entry = 125109;
UPDATE world.creature_template_wdb SET Name1 = 'Wrathful Ember' WHERE Entry = 125110;
UPDATE world.creature_template_wdb SET Name1 = 'Vanguard Portal-Master', NameAlt1 = '' WHERE Entry = 125151;
UPDATE world.creature_template_wdb SET Name1 = 'Vanguard Scout', NameAlt1 = '' WHERE Entry = 125152;
UPDATE world.creature_template_wdb SET Name1 = 'Alleria Windrunner' WHERE Entry = 125443;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Stalker' WHERE Entry = 125880;
UPDATE world.creature_template_wdb SET Name1 = 'Brood of Ven''orn' WHERE Entry = 126111;
UPDATE world.creature_template_wdb SET Name1 = 'Vile Felspitter' WHERE Entry = 126114;
UPDATE world.creature_template_wdb SET Name1 = 'Voracious Scavenger' WHERE Entry = 126174;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Defender' WHERE Entry = 126193;
UPDATE world.creature_template_wdb SET Name1 = 'Admiral Svirax' WHERE Entry = 126258;
UPDATE world.creature_template_wdb SET Name1 = 'Vindicaar Matrix Core' WHERE Entry = 126425;
UPDATE world.creature_template_wdb SET Name1 = 'Turek the Lucid' WHERE Entry = 126868;
UPDATE world.creature_template_wdb SET Name1 = 'Instructor Tarahna' WHERE Entry = 126900;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Soul Harvester' WHERE Entry = 126943;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127135;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127137;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127146;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Soulshaper', NameAlt1 = '' WHERE Entry = 127162;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127501;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127504;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127505;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Stalker' WHERE Entry = 127640;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Clutch-Sister' WHERE Entry = 127857;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127994;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127996;
UPDATE world.creature_template_wdb SET Name1 = 'Pile of Stones' WHERE Entry = 127997;
UPDATE world.creature_template_wdb SET Name1 = 'Ruinhoof' WHERE Entry = 128007;
UPDATE world.creature_template_wdb SET Name1 = 'Foulclaw' WHERE Entry = 128008;
UPDATE world.creature_template_wdb SET Name1 = 'Baneglow' WHERE Entry = 128009;
UPDATE world.creature_template_wdb SET Name1 = 'Retch' WHERE Entry = 128010;
UPDATE world.creature_template_wdb SET Name1 = 'Deathscreech' WHERE Entry = 128011;
UPDATE world.creature_template_wdb SET Name1 = 'Gnasher' WHERE Entry = 128012;
UPDATE world.creature_template_wdb SET Name1 = 'Bucky' WHERE Entry = 128013;
UPDATE world.creature_template_wdb SET Name1 = 'Snozz' WHERE Entry = 128014;
UPDATE world.creature_template_wdb SET Name1 = 'Gloamwing' WHERE Entry = 128015;
UPDATE world.creature_template_wdb SET Name1 = 'Shadeflicker' WHERE Entry = 128016;
UPDATE world.creature_template_wdb SET Name1 = 'Corrupted Blood of Argus' WHERE Entry = 128017;
UPDATE world.creature_template_wdb SET Name1 = 'Mar''cuus' WHERE Entry = 128018;
UPDATE world.creature_template_wdb SET Name1 = 'Watcher' WHERE Entry = 128019;
UPDATE world.creature_template_wdb SET Name1 = 'Bloat' WHERE Entry = 128020;
UPDATE world.creature_template_wdb SET Name1 = 'Earseeker' WHERE Entry = 128021;
UPDATE world.creature_template_wdb SET Name1 = 'Pilfer' WHERE Entry = 128022;
UPDATE world.creature_template_wdb SET Name1 = 'One-of-Many' WHERE Entry = 128024;
UPDATE world.creature_template_wdb SET Name1 = 'Bile Larva' WHERE Entry = 128162;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Bile Larva' WHERE Entry = 128163;
UPDATE world.creature_template_wdb SET Name1 = 'Bilescourge' WHERE Entry = 128164;
UPDATE world.creature_template_wdb SET Name1 = 'Flickering Argunite' WHERE Entry = 128166;
UPDATE world.creature_template_wdb SET Name1 = 'Skyfin Juvenile' WHERE Entry = 128167;
UPDATE world.creature_template_wdb SET Name1 = 'Warpstalker Runt' WHERE Entry = 128170;
UPDATE world.creature_template_wdb SET Name1 = 'Arcane Gorger' WHERE Entry = 128172;
UPDATE world.creature_template_wdb SET Name1 = 'Pygmy Marsuul' WHERE Entry = 128173;
UPDATE world.creature_template_wdb SET Name1 = 'Felcrazed Wyrm' WHERE Entry = 128174;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Bilescourge' WHERE Entry = 128175;

-- English from creature_template_wdb_locale (enUS rows; retail names)
UPDATE world.creature_template_wdb SET Name1 = 'Warhorse' WHERE Entry = 9158;
UPDATE world.creature_template_wdb SET Name1 = 'Venomtip Scorpid' WHERE Entry = 9691;
UPDATE world.creature_template_wdb SET Name1 = 'Dustwraith' WHERE Entry = 10081;
UPDATE world.creature_template_wdb SET Name1 = 'The Beast' WHERE Entry = 10430;
UPDATE world.creature_template_wdb SET Name1 = 'The Kurken' WHERE Entry = 17447;
UPDATE world.creature_template_wdb SET Name1 = 'Spawn of Uvuros' WHERE Entry = 21108;
UPDATE world.creature_template_wdb SET Name1 = 'Army of the Dead' WHERE Entry = 24207;
UPDATE world.creature_template_wdb SET Name1 = 'Icepaw Bear' WHERE Entry = 29319;
UPDATE world.creature_template_wdb SET Name1 = 'King Krush' WHERE Entry = 32485;
UPDATE world.creature_template_wdb SET Name1 = 'Mirror Image' WHERE Entry = 47244;
UPDATE world.creature_template_wdb SET Name1 = 'Ronak' WHERE Entry = 50346;
UPDATE world.creature_template_wdb SET Name1 = 'Azelisk' WHERE Entry = 50725;
UPDATE world.creature_template_wdb SET Name1 = 'Ankha' WHERE Entry = 54318;
UPDATE world.creature_template_wdb SET Name1 = 'Lotus Crane' WHERE Entry = 59786;
UPDATE world.creature_template_wdb SET Name1 = 'Fire Spirit' WHERE Entry = 69791;
UPDATE world.creature_template_wdb SET Name1 = 'Earth Spirit' WHERE Entry = 69792;
UPDATE world.creature_template_wdb SET Name1 = 'Primal Direhorn Hatchling' WHERE Entry = 70012;
UPDATE world.creature_template_wdb SET Name1 = 'Thok the Bloodthirsty' WHERE Entry = 71529;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Aquamancer', NameAlt1 = '' WHERE Entry = 74353;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Shadow', NameAlt1 = '' WHERE Entry = 74363;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Shadowmage', NameAlt1 = '' WHERE Entry = 74382;
UPDATE world.creature_template_wdb SET Name1 = 'Thruk' WHERE Entry = 74505;
UPDATE world.creature_template_wdb SET Name1 = 'Guardian of the Deep' WHERE Entry = 74508;
UPDATE world.creature_template_wdb SET Name1 = 'Blue Shale Crawler' WHERE Entry = 74509;
UPDATE world.creature_template_wdb SET Name1 = 'Executioner Gore' WHERE Entry = 74518;
UPDATE world.creature_template_wdb SET Name1 = 'Aqua Guardian' WHERE Entry = 74716;
UPDATE world.creature_template_wdb SET Name1 = 'Blindlight Rotmouth' WHERE Entry = 74719;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Lord Bathiel' WHERE Entry = 74728;
UPDATE world.creature_template_wdb SET Name1 = 'Voidwalker Minion' WHERE Entry = 74729;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror', Title = 'Aspect of Aku''mai' WHERE Entry = 74747;
UPDATE world.creature_template_wdb SET Name1 = 'Voidwalker Minion' WHERE Entry = 74861;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Man' WHERE Entry = 74997;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Storm Mender' WHERE Entry = 75011;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Disciple', NameAlt1 = '' WHERE Entry = 75012;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Tormentor', NameAlt1 = '' WHERE Entry = 75034;
UPDATE world.creature_template_wdb SET Name1 = 'Frightened Prisoner', NameAlt1 = '' WHERE Entry = 75039;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Man' WHERE Entry = 75042;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror', Title = 'Aspect of Aku''mai' WHERE Entry = 75046;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Aquamancer' WHERE Entry = 75058;
UPDATE world.creature_template_wdb SET Name1 = 'Slain Hero' WHERE Entry = 75060;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror' WHERE Entry = 75086;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror', Title = 'Aspect of Aku''mai' WHERE Entry = 75090;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror' WHERE Entry = 75111;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Man' WHERE Entry = 75147;
UPDATE world.creature_template_wdb SET Name1 = 'Aku''mai the Devourer', Title = 'Terror from the Deep' WHERE Entry = 75155;
UPDATE world.creature_template_wdb SET Name1 = 'Aku''mai the Venomous', Title = 'Terror from the Deep' WHERE Entry = 75157;
UPDATE world.creature_template_wdb SET Name1 = 'Aku''mai' WHERE Entry = 75158;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror', Title = 'Aspect of Aku''mai' WHERE Entry = 75172;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Storm Mender', NameAlt1 = '' WHERE Entry = 75285;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Man' WHERE Entry = 75307;
UPDATE world.creature_template_wdb SET Name1 = 'Aku''mai' WHERE Entry = 75408;
UPDATE world.creature_template_wdb SET Name1 = 'Guardian of the Deep' WHERE Entry = 75410;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror', Title = 'Aspect of Aku''mai' WHERE Entry = 75463;
UPDATE world.creature_template_wdb SET Name1 = 'Domina' WHERE Entry = 75550;
UPDATE world.creature_template_wdb SET Name1 = 'Subjugator Kor''ul' WHERE Entry = 75553;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Man' WHERE Entry = 75575;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror' WHERE Entry = 75780;
UPDATE world.creature_template_wdb SET Name1 = 'Deep Terror', Title = 'Aspect of Aku''mai' WHERE Entry = 75781;
UPDATE world.creature_template_wdb SET Name1 = 'Invisible Man' WHERE Entry = 75923;
UPDATE world.creature_template_wdb SET Name1 = 'Lady Sarevess' WHERE Entry = 76005;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Shadow', NameAlt1 = '' WHERE Entry = 76036;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Storm Mender', NameAlt1 = '' WHERE Entry = 76037;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Shadowmage', NameAlt1 = '' WHERE Entry = 76038;
UPDATE world.creature_template_wdb SET Name1 = 'Twilight Aquamancer', NameAlt1 = '' WHERE Entry = 76039;
UPDATE world.creature_template_wdb SET Name1 = 'Guardian Eggs' WHERE Entry = 76062;
UPDATE world.creature_template_wdb SET Name1 = 'Pahboo-Ra', Title = 'Son of Ghamoo-Ra' WHERE Entry = 76954;
UPDATE world.creature_template_wdb SET Name1 = 'The Old Gods' WHERE Entry = 85844;
UPDATE world.creature_template_wdb SET Name1 = 'Blacksmithing Follower - Alliance', Title = 'Blacksmith', TitleAlt = '' WHERE Entry = 88403;
UPDATE world.creature_template_wdb SET Name1 = 'Gara' WHERE Entry = 88708;
UPDATE world.creature_template_wdb SET Name1 = 'Dark Minion' WHERE Entry = 94072;
UPDATE world.creature_template_wdb SET Name1 = 'Unstable Tear' WHERE Entry = 94584;
UPDATE world.creature_template_wdb SET Name1 = 'Greater Lightning Elemental' WHERE Entry = 97022;
UPDATE world.creature_template_wdb SET Name1 = 'Wind Spirit' WHERE Entry = 99625;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowy Tear' WHERE Entry = 99887;
UPDATE world.creature_template_wdb SET Name1 = 'T''uure' WHERE Entry = 99904;
UPDATE world.creature_template_wdb SET Name1 = 'Spitting Cobra' WHERE Entry = 104493;
UPDATE world.creature_template_wdb SET Name1 = 'Windfury Totem' WHERE Entry = 105690;
UPDATE world.creature_template_wdb SET Name1 = 'Akaari''s Soul' WHERE Entry = 105850;
UPDATE world.creature_template_wdb SET Name1 = 'Ox Initiate' WHERE Entry = 106812;
UPDATE world.creature_template_wdb SET Name1 = 'Taran Zhu', Title = 'Lord of the Shado-Pan' WHERE Entry = 107022;
UPDATE world.creature_template_wdb SET Name1 = 'Treble' WHERE Entry = 107951;
UPDATE world.creature_template_wdb SET Name1 = 'Chaos Tear' WHERE Entry = 108493;
UPDATE world.creature_template_wdb SET Name1 = 'Spawn of Serpentrix' WHERE Entry = 108655;
UPDATE world.creature_template_wdb SET Name1 = 'Black Harvest Invoker' WHERE Entry = 108799;
UPDATE world.creature_template_wdb SET Name1 = 'Earthcaller' WHERE Entry = 109448;
UPDATE world.creature_template_wdb SET Name1 = 'Earthen Ring Geomancer' WHERE Entry = 109577;
UPDATE world.creature_template_wdb SET Name1 = 'Druid of the Claw' WHERE Entry = 109839;
UPDATE world.creature_template_wdb SET Name1 = 'Mylune' WHERE Entry = 110056;
UPDATE world.creature_template_wdb SET Name1 = 'Faerie Dragon', Title = 'Mylune''s Minion' WHERE Entry = 110061;
UPDATE world.creature_template_wdb SET Name1 = 'Unseen Marksman' WHERE Entry = 110456;
UPDATE world.creature_template_wdb SET Name1 = 'Kirin Tor Invoker' WHERE Entry = 110715;
UPDATE world.creature_template_wdb SET Name1 = 'Tirisgarde Apprentice' WHERE Entry = 110750;
UPDATE world.creature_template_wdb SET Name1 = 'Unseen Pathfinder' WHERE Entry = 110975;
UPDATE world.creature_template_wdb SET Name1 = 'Leokk' WHERE Entry = 111014;
UPDATE world.creature_template_wdb SET Name1 = 'Defias Thief' WHERE Entry = 111254;
UPDATE world.creature_template_wdb SET Name1 = 'Silver Hand Knight' WHERE Entry = 111292;
UPDATE world.creature_template_wdb SET Name1 = 'Silver Hand Templar' WHERE Entry = 111316;
UPDATE world.creature_template_wdb SET Name1 = 'Generic Bunny' WHERE Entry = 111345;
UPDATE world.creature_template_wdb SET Name1 = 'Dark Zealot' WHERE Entry = 111506;
UPDATE world.creature_template_wdb SET Name1 = 'Lightspawn' WHERE Entry = 111510;
UPDATE world.creature_template_wdb SET Name1 = 'Acherus Death Knight' WHERE Entry = 111694;
UPDATE world.creature_template_wdb SET Name1 = 'Debilitating Eye' WHERE Entry = 111756;
UPDATE world.creature_template_wdb SET Name1 = 'Ashtongue Warrior' WHERE Entry = 111912;
UPDATE world.creature_template_wdb SET Name1 = 'Iron Dwarf' WHERE Entry = 111914;
UPDATE world.creature_template_wdb SET Name1 = 'Illidari Adept' WHERE Entry = 111962;
UPDATE world.creature_template_wdb SET Name1 = 'Akama' WHERE Entry = 112476;
UPDATE world.creature_template_wdb SET Name1 = 'Plucky' WHERE Entry = 113890;
UPDATE world.creature_template_wdb SET Name1 = 'Generic Bunny' WHERE Entry = 114590;
UPDATE world.creature_template_wdb SET Name1 = 'Orphaned Snowfeather' WHERE Entry = 115737;
UPDATE world.creature_template_wdb SET Name1 = 'Orphaned Sharptalon' WHERE Entry = 115740;
UPDATE world.creature_template_wdb SET Name1 = 'Orphaned Bloodgazer' WHERE Entry = 115741;
UPDATE world.creature_template_wdb SET Name1 = 'Felfire Imp' WHERE Entry = 117172;
UPDATE world.creature_template_wdb SET Name1 = 'Fiery Trickster' WHERE Entry = 117173;
UPDATE world.creature_template_wdb SET Name1 = 'Sickly Imp' WHERE Entry = 117174;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowflame Imp' WHERE Entry = 117175;
UPDATE world.creature_template_wdb SET Name1 = 'Felstalker' WHERE Entry = 117176;
UPDATE world.creature_template_wdb SET Name1 = 'Dreadstalker' WHERE Entry = 117177;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowstalker' WHERE Entry = 117178;
UPDATE world.creature_template_wdb SET Name1 = 'Dreadscar Trickster' WHERE Entry = 117626;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 118830;
UPDATE world.creature_template_wdb SET Name1 = 'Shieldbearer' WHERE Entry = 119074;
UPDATE world.creature_template_wdb SET Name1 = 'Marcus "Bagman" Brown' WHERE Entry = 119390;
UPDATE world.creature_template_wdb SET Name1 = 'Darkfallen Refugee' WHERE Entry = 119391;
UPDATE world.creature_template_wdb SET Name1 = 'Ke''nath', Title = 'General Goods' WHERE Entry = 119393;
UPDATE world.creature_template_wdb SET Name1 = 'Marcus "Bagman" Brown' WHERE Entry = 119399;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Doomcaller' WHERE Entry = 119533;
UPDATE world.creature_template_wdb SET Name1 = 'Archmage Khadgar' WHERE Entry = 119538;
UPDATE world.creature_template_wdb SET Name1 = 'Vilefiend' WHERE Entry = 119576;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Champion' WHERE Entry = 119597;
UPDATE world.creature_template_wdb SET Name1 = 'Scarwing Harrier' WHERE Entry = 119604;
UPDATE world.creature_template_wdb SET Name1 = 'Marsuul Kit' WHERE Entry = 119745;
UPDATE world.creature_template_wdb SET Name1 = 'Voidstalker' WHERE Entry = 119747;
UPDATE world.creature_template_wdb SET Name1 = 'Skyfin Mana Ray' WHERE Entry = 119748;
UPDATE world.creature_template_wdb SET Name1 = 'Voidscarred Krokul' WHERE Entry = 119749;
UPDATE world.creature_template_wdb SET Name1 = 'Fanatical Echo' WHERE Entry = 119864;
UPDATE world.creature_template_wdb SET Name1 = 'Fanatical Echo' WHERE Entry = 119866;
UPDATE world.creature_template_wdb SET Name1 = 'Horrified Echo' WHERE Entry = 119868;
UPDATE world.creature_template_wdb SET Name1 = 'Horrified Echo' WHERE Entry = 119870;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Ruinstalker' WHERE Entry = 119884;
UPDATE world.creature_template_wdb SET Name1 = 'Flashfoot Marsuul' WHERE Entry = 119968;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Skyfin' WHERE Entry = 119969;
UPDATE world.creature_template_wdb SET Name1 = 'Archmage Khadgar' WHERE Entry = 120224;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Champion' WHERE Entry = 120322;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Champion', NameAlt1 = '' WHERE Entry = 120329;
UPDATE world.creature_template_wdb SET Name1 = 'Vilefiend' WHERE Entry = 120330;
UPDATE world.creature_template_wdb SET Name1 = 'Garothi Obliterator' WHERE Entry = 120354;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Conqueror' WHERE Entry = 120395;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Pylon' WHERE Entry = 120536;
UPDATE world.creature_template_wdb SET Name1 = 'Argunite Matrix' WHERE Entry = 120573;
UPDATE world.creature_template_wdb SET Name1 = 'Xeth''tal' WHERE Entry = 120598;
UPDATE world.creature_template_wdb SET Name1 = 'Magraloth' WHERE Entry = 120601;
UPDATE world.creature_template_wdb SET Name1 = 'Kar''aaz' WHERE Entry = 120602;
UPDATE world.creature_template_wdb SET Name1 = 'Zealous Echo' WHERE Entry = 120603;
UPDATE world.creature_template_wdb SET Name1 = 'Zealous Echo' WHERE Entry = 120604;
UPDATE world.creature_template_wdb SET Name1 = 'Felflame Scavenger' WHERE Entry = 120638;
UPDATE world.creature_template_wdb SET Name1 = 'Stalwart Echo' WHERE Entry = 120689;
UPDATE world.creature_template_wdb SET Name1 = 'Stalwart Echo' WHERE Entry = 120690;
UPDATE world.creature_template_wdb SET Name1 = 'High Exarch Turalyon' WHERE Entry = 120763;
UPDATE world.creature_template_wdb SET Name1 = 'Soultwisted Echo' WHERE Entry = 120836;
UPDATE world.creature_template_wdb SET Name1 = 'Echo of Argus', NameAlt1 = '' WHERE Entry = 120875;
UPDATE world.creature_template_wdb SET Name1 = 'Echo of Argus' WHERE Entry = 120876;
UPDATE world.creature_template_wdb SET Name1 = 'Echo of Argus' WHERE Entry = 120877;
UPDATE world.creature_template_wdb SET Name1 = 'Echo of Argus' WHERE Entry = 120883;
UPDATE world.creature_template_wdb SET Name1 = 'Echo of Argus' WHERE Entry = 120884;
UPDATE world.creature_template_wdb SET Name1 = 'Darkfallen Slave' WHERE Entry = 121174;
UPDATE world.creature_template_wdb SET Name1 = 'Darkfallen Slave' WHERE Entry = 121175;
UPDATE world.creature_template_wdb SET Name1 = 'Alleria Windrunner' WHERE Entry = 121230;
UPDATE world.creature_template_wdb SET Name1 = 'Darkfallen Slave' WHERE Entry = 121246;
UPDATE world.creature_template_wdb SET Name1 = 'Void-Addled Krokul' WHERE Entry = 121251;
UPDATE world.creature_template_wdb SET Name1 = 'Slavering Devourer' WHERE Entry = 121297;
UPDATE world.creature_template_wdb SET Name1 = 'Aethas Sunreaver' WHERE Entry = 121359;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Bulwark', NameAlt1 = '' WHERE Entry = 121394;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Dragoon', NameAlt1 = '' WHERE Entry = 121395;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Sharpshooter', NameAlt1 = '' WHERE Entry = 121396;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Warpriest', NameAlt1 = '' WHERE Entry = 121397;
UPDATE world.creature_template_wdb SET Name1 = 'Blademaster Telaamon' WHERE Entry = 121398;
UPDATE world.creature_template_wdb SET Name1 = 'Arator the Redeemer' WHERE Entry = 121408;
UPDATE world.creature_template_wdb SET Name1 = 'Vindicator Boros' WHERE Entry = 121410;
UPDATE world.creature_template_wdb SET Name1 = 'Vereesa Windrunner', Title = 'Ranger-General of the Silver Covenant' WHERE Entry = 121417;
UPDATE world.creature_template_wdb SET Name1 = 'Lady Liadrin', Title = 'Blood Knight Matriarch' WHERE Entry = 121418;
UPDATE world.creature_template_wdb SET Name1 = 'Silgryn' WHERE Entry = 121421;
UPDATE world.creature_template_wdb SET Name1 = 'Kal', Title = 'Silgryn''s Companion' WHERE Entry = 121423;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Pilot' WHERE Entry = 121464;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Battlemage', NameAlt1 = '' WHERE Entry = 121516;
UPDATE world.creature_template_wdb SET Name1 = 'Baraat the Longshot' WHERE Entry = 121517;
UPDATE world.creature_template_wdb SET Name1 = 'Captain Fareeya', Title = 'The Crescent Glaive' WHERE Entry = 121519;
UPDATE world.creature_template_wdb SET Name1 = 'Grand Lector Enaara' WHERE Entry = 121520;
UPDATE world.creature_template_wdb SET Name1 = 'Grand Vindicator Sorvos' WHERE Entry = 121521;
UPDATE world.creature_template_wdb SET Name1 = 'Felscarred Destroyer' WHERE Entry = 121531;
UPDATE world.creature_template_wdb SET Name1 = 'Soulripper Warfiend' WHERE Entry = 121534;
UPDATE world.creature_template_wdb SET Name1 = 'Citadel Dreadguard' WHERE Entry = 121536;
UPDATE world.creature_template_wdb SET Name1 = 'High Inquisitor Raalgar' WHERE Entry = 121544;
UPDATE world.creature_template_wdb SET Name1 = 'Shield' WHERE Entry = 121545;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Warframe' WHERE Entry = 121547;
UPDATE world.creature_template_wdb SET Name1 = 'Foebreaker Vanguard' WHERE Entry = 121548;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowcrazed Marsuul' WHERE Entry = 121562;
UPDATE world.creature_template_wdb SET Name1 = 'Highguard Warrior' WHERE Entry = 121575;
UPDATE world.creature_template_wdb SET Name1 = 'Archmage Y''mera' WHERE Entry = 121578;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Battery' WHERE Entry = 121587;
UPDATE world.creature_template_wdb SET Name1 = 'Thaumaturge Vashreen', Title = 'Purveyor of Exquisite Furnishings' WHERE Entry = 121589;
UPDATE world.creature_template_wdb SET Name1 = 'Enthralled Voidstalker' WHERE Entry = 121629;
UPDATE world.creature_template_wdb SET Name1 = 'Sneaky Snake' WHERE Entry = 121661;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowguard Phaseblade' WHERE Entry = 121672;
UPDATE world.creature_template_wdb SET Name1 = 'Voidgorged Stalker' WHERE Entry = 121673;
UPDATE world.creature_template_wdb SET Name1 = 'Creeping Gloom' WHERE Entry = 122014;
UPDATE world.creature_template_wdb SET Name1 = 'Void Streaker' WHERE Entry = 122015;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Cannoneer' WHERE Entry = 122039;
UPDATE world.creature_template_wdb SET Name1 = 'Shademistress' WHERE Entry = 122041;
UPDATE world.creature_template_wdb SET Name1 = 'Argus Storm' WHERE Entry = 122304;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Argus Construct' WHERE Entry = 122353;
UPDATE world.creature_template_wdb SET Name1 = 'Forgotten Denizen' WHERE Entry = 122357;
UPDATE world.creature_template_wdb SET Name1 = 'Forgotten Denizen' WHERE Entry = 122358;
UPDATE world.creature_template_wdb SET Name1 = 'Lingering Merchant' WHERE Entry = 122359;
UPDATE world.creature_template_wdb SET Name1 = 'Youthful Vestige', NameAlt1 = '' WHERE Entry = 122360;
UPDATE world.creature_template_wdb SET Name1 = 'Lingering Merchant' WHERE Entry = 122361;
UPDATE world.creature_template_wdb SET Name1 = 'Silentfoot Panthara' WHERE Entry = 122362;
UPDATE world.creature_template_wdb SET Name1 = 'Marsuul Kit' WHERE Entry = 122364;
UPDATE world.creature_template_wdb SET Name1 = 'Haywire Argus Construct' WHERE Entry = 122368;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowguard Conjurer' WHERE Entry = 122405;
UPDATE world.creature_template_wdb SET Name1 = 'Bound Voidlord' WHERE Entry = 122412;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 122509;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Pilot' WHERE Entry = 122622;
UPDATE world.creature_template_wdb SET Name1 = 'Abandoned Altar' WHERE Entry = 122768;
UPDATE world.creature_template_wdb SET Name1 = 'Defaced Naaru Figurine' WHERE Entry = 122769;
UPDATE world.creature_template_wdb SET Name1 = 'Frantic Wall Scrawlings' WHERE Entry = 122770;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Battery' WHERE Entry = 122794;
UPDATE world.creature_template_wdb SET Name1 = 'Ur''zul Devourer' WHERE Entry = 122815;
UPDATE world.creature_template_wdb SET Name1 = 'Lady Shahrazad' WHERE Entry = 122834;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Soulshaper' WHERE Entry = 122835;
UPDATE world.creature_template_wdb SET Name1 = 'Captured Krokul' WHERE Entry = 122837;
UPDATE world.creature_template_wdb SET Name1 = 'Ur''zul Devourer' WHERE Entry = 122891;
UPDATE world.creature_template_wdb SET Name1 = 'Argus Rift' WHERE Entry = 122902;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Doomcaller' WHERE Entry = 122922;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Conqueror' WHERE Entry = 122924;
UPDATE world.creature_template_wdb SET Name1 = 'Isolon Devout' WHERE Entry = 122945;
UPDATE world.creature_template_wdb SET Name1 = 'Voidling' WHERE Entry = 122946;
UPDATE world.creature_template_wdb SET Name1 = 'Tortured Slave' WHERE Entry = 122974;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Doomcaller', NameAlt1 = '' WHERE Entry = 122993;
UPDATE world.creature_template_wdb SET Name1 = 'Forsaken Eredar' WHERE Entry = 123025;
UPDATE world.creature_template_wdb SET Name1 = 'Val''aan', Title = 'Repairs' WHERE Entry = 123061;
UPDATE world.creature_template_wdb SET Name1 = 'Wild Cragscaler' WHERE Entry = 123074;
UPDATE world.creature_template_wdb SET Name1 = 'Duskcloak Alpha' WHERE Entry = 123076;
UPDATE world.creature_template_wdb SET Name1 = 'Fel Crystal' WHERE Entry = 123084;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Acolyte', NameAlt1 = '' WHERE Entry = 123130;
UPDATE world.creature_template_wdb SET Name1 = 'Navigation Console' WHERE Entry = 123139;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 123258;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 123260;
UPDATE world.creature_template_wdb SET Name1 = 'Void-Addled Krokul' WHERE Entry = 123302;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Wrangler' WHERE Entry = 123389;
UPDATE world.creature_template_wdb SET Name1 = 'Cragscaler Steed' WHERE Entry = 123390;
UPDATE world.creature_template_wdb SET Name1 = 'High Priestess Ishanah', Title = 'Innkeeper' WHERE Entry = 123395;
UPDATE world.creature_template_wdb SET Name1 = 'Archmage Y''mera' WHERE Entry = 123413;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Champion' WHERE Entry = 123418;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Doomcaller' WHERE Entry = 123420;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Doomcaller' WHERE Entry = 123421;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Champion' WHERE Entry = 123422;
UPDATE world.creature_template_wdb SET Name1 = 'Augari Novitiate' WHERE Entry = 123471;
UPDATE world.creature_template_wdb SET Name1 = 'Augari Novitiate' WHERE Entry = 123472;
UPDATE world.creature_template_wdb SET Name1 = 'Augari Summoner' WHERE Entry = 123505;
UPDATE world.creature_template_wdb SET Name1 = 'Augari Summoner' WHERE Entry = 123506;
UPDATE world.creature_template_wdb SET Name1 = 'Restless Arcane Familiar' WHERE Entry = 123507;
UPDATE world.creature_template_wdb SET Name1 = 'Manafeeder Panthara' WHERE Entry = 123508;
UPDATE world.creature_template_wdb SET Name1 = 'Arcfin Mana Ray' WHERE Entry = 123511;
UPDATE world.creature_template_wdb SET Name1 = 'Magechaser Marsuul' WHERE Entry = 123512;
UPDATE world.creature_template_wdb SET Name1 = 'Arc-Consul Velara' WHERE Entry = 123520;
UPDATE world.creature_template_wdb SET Name1 = 'Grand Vizier Jarasum' WHERE Entry = 123521;
UPDATE world.creature_template_wdb SET Name1 = 'High Wakener Aargon' WHERE Entry = 123522;
UPDATE world.creature_template_wdb SET Name1 = 'Chitinbuk Grazer' WHERE Entry = 123527;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Laborer' WHERE Entry = 123565;
UPDATE world.creature_template_wdb SET Name1 = 'Arcane Familiar' WHERE Entry = 123567;
UPDATE world.creature_template_wdb SET Name1 = 'Soulbonded Construct' WHERE Entry = 123574;
UPDATE world.creature_template_wdb SET Name1 = 'Lingering Aether' WHERE Entry = 123629;
UPDATE world.creature_template_wdb SET Name1 = 'Highguard Captain' WHERE Entry = 123658;
UPDATE world.creature_template_wdb SET Name1 = 'Highguard Watcher' WHERE Entry = 123659;
UPDATE world.creature_template_wdb SET Name1 = 'Captain Fareeya', Title = 'The Crescent Glaive' WHERE Entry = 123668;
UPDATE world.creature_template_wdb SET Name1 = 'Grand Vindicator Sorvos' WHERE Entry = 123669;
UPDATE world.creature_template_wdb SET Name1 = 'Baraat the Longshot' WHERE Entry = 123670;
UPDATE world.creature_template_wdb SET Name1 = 'Blademaster Telaamon' WHERE Entry = 123671;
UPDATE world.creature_template_wdb SET Name1 = 'Archmage Y''mera' WHERE Entry = 123679;
UPDATE world.creature_template_wdb SET Name1 = 'Frenzied Marsuul Kit' WHERE Entry = 123764;
UPDATE world.creature_template_wdb SET Name1 = 'Quartermistress Kl''azz' WHERE Entry = 124015;
UPDATE world.creature_template_wdb SET Name1 = 'Bile Larva' WHERE Entry = 124046;
UPDATE world.creature_template_wdb SET Name1 = 'Bilescourge' WHERE Entry = 124051;
UPDATE world.creature_template_wdb SET Name1 = 'Vigilant Quoram', Title = 'The Gatekeeper' WHERE Entry = 124070;
UPDATE world.creature_template_wdb SET Name1 = 'Failed Convert' WHERE Entry = 124208;
UPDATE world.creature_template_wdb SET Name1 = 'Chitinous Cragscaler' WHERE Entry = 124225;
UPDATE world.creature_template_wdb SET Name1 = 'Chitinous Cragscaler' WHERE Entry = 124265;
UPDATE world.creature_template_wdb SET Name1 = 'Panthara Apex' WHERE Entry = 124269;
UPDATE world.creature_template_wdb SET Name1 = 'Panthara Stalker' WHERE Entry = 124271;
UPDATE world.creature_template_wdb SET Name1 = 'Felscarred Marsuul' WHERE Entry = 124278;
UPDATE world.creature_template_wdb SET Name1 = 'Argus Darkray' WHERE Entry = 124279;
UPDATE world.creature_template_wdb SET Name1 = 'Volatile Devastator Rounds' WHERE Entry = 124294;
UPDATE world.creature_template_wdb SET Name1 = 'Duskcloak Panthara' WHERE Entry = 124303;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 124313;
UPDATE world.creature_template_wdb SET Name1 = 'Darkfallen Cragscaler' WHERE Entry = 124348;
UPDATE world.creature_template_wdb SET Name1 = 'Vilefiend Tracker' WHERE Entry = 124430;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Drudge' WHERE Entry = 124432;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Fiendmaster', NameAlt1 = '' WHERE Entry = 124435;
UPDATE world.creature_template_wdb SET Name1 = 'Wild Cragscaler' WHERE Entry = 124439;
UPDATE world.creature_template_wdb SET Name1 = 'Overseer Y''Beda' WHERE Entry = 124440;
UPDATE world.creature_template_wdb SET Name1 = 'Demonfly Acidmaw' WHERE Entry = 124444;
UPDATE world.creature_template_wdb SET Name1 = 'Acidmaw Larva' WHERE Entry = 124446;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Despoiler', NameAlt1 = '' WHERE Entry = 124448;
UPDATE world.creature_template_wdb SET Name1 = 'High Exarch Turalyon' WHERE Entry = 124477;
UPDATE world.creature_template_wdb SET Name1 = 'Young Duskcloak' WHERE Entry = 124486;
UPDATE world.creature_template_wdb SET Name1 = 'Locus-Walker' WHERE Entry = 124545;
UPDATE world.creature_template_wdb SET Name1 = 'Power Conduit' WHERE Entry = 124558;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 124569;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Overseer' WHERE Entry = 124670;
UPDATE world.creature_template_wdb SET Name1 = 'Mo''arg Pit Boss' WHERE Entry = 124687;
UPDATE world.creature_template_wdb SET Name1 = 'Petrified Cragscaler' WHERE Entry = 124711;
UPDATE world.creature_template_wdb SET Name1 = 'Petrified Duskcloak' WHERE Entry = 124738;
UPDATE world.creature_template_wdb SET Name1 = 'Empowered Arcane Familiar' WHERE Entry = 124760;
UPDATE world.creature_template_wdb SET Name1 = 'Soulbonded Construct' WHERE Entry = 124773;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Warrior' WHERE Entry = 124833;
UPDATE world.creature_template_wdb SET Name1 = 'Injured Krokul' WHERE Entry = 124834;
UPDATE world.creature_template_wdb SET Name1 = 'Shield' WHERE Entry = 124997;
UPDATE world.creature_template_wdb SET Name1 = 'Shield' WHERE Entry = 124998;
UPDATE world.creature_template_wdb SET Name1 = 'Shield' WHERE Entry = 124999;
UPDATE world.creature_template_wdb SET Name1 = 'Apocalypse Shard' WHERE Entry = 125032;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Crusher' WHERE Entry = 125056;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Ridgestalker' WHERE Entry = 125058;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Wrangler' WHERE Entry = 125061;
UPDATE world.creature_template_wdb SET Name1 = 'Chitinous Cragscaler' WHERE Entry = 125062;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Wrangler' WHERE Entry = 125063;
UPDATE world.creature_template_wdb SET Name1 = 'Void Portal' WHERE Entry = 125102;
UPDATE world.creature_template_wdb SET Name1 = 'Igneous Crusher' WHERE Entry = 125103;
UPDATE world.creature_template_wdb SET Name1 = 'Mistress Apostriss' WHERE Entry = 125114;
UPDATE world.creature_template_wdb SET Name1 = 'Lady Heretica' WHERE Entry = 125115;
UPDATE world.creature_template_wdb SET Name1 = 'Nath''raxxan Fleshcarver' WHERE Entry = 125121;
UPDATE world.creature_template_wdb SET Name1 = 'Nath''raxxan Doomshot' WHERE Entry = 125129;
UPDATE world.creature_template_wdb SET Name1 = 'Nathrezim Banelord' WHERE Entry = 125139;
UPDATE world.creature_template_wdb SET Name1 = 'Hunting Soulseeker' WHERE Entry = 125146;
UPDATE world.creature_template_wdb SET Name1 = 'Ravenous Soulhunter' WHERE Entry = 125223;
UPDATE world.creature_template_wdb SET Name1 = 'Gaal', Title = 'Blacksmith' WHERE Entry = 125246;
UPDATE world.creature_template_wdb SET Name1 = 'Archivist Ionaa' WHERE Entry = 125247;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Guardian' WHERE Entry = 125248;
UPDATE world.creature_template_wdb SET Name1 = 'Fel Devastator' WHERE Entry = 125265;
UPDATE world.creature_template_wdb SET Name1 = 'Nath''raxxan Doomshot' WHERE Entry = 125290;
UPDATE world.creature_template_wdb SET Name1 = 'Nath''raxxan Fleshcarver' WHERE Entry = 125292;
UPDATE world.creature_template_wdb SET Name1 = 'Nath''raxxan Pyroclast' WHERE Entry = 125294;
UPDATE world.creature_template_wdb SET Name1 = 'Khamir', Title = 'Master Blacksmith' WHERE Entry = 125341;
UPDATE world.creature_template_wdb SET Name1 = 'Vorel', Title = 'Master Jewelcrafter' WHERE Entry = 125343;
UPDATE world.creature_template_wdb SET Name1 = 'Alchemist Funen' WHERE Entry = 125346;
UPDATE world.creature_template_wdb SET Name1 = 'Enstraa', Title = 'Master Leatherworker' WHERE Entry = 125349;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 125350;
UPDATE world.creature_template_wdb SET Name1 = 'Khaela', Title = 'Master Tailor' WHERE Entry = 125351;
UPDATE world.creature_template_wdb SET Name1 = 'Unstable Felshard' WHERE Entry = 125387;
UPDATE world.creature_template_wdb SET Name1 = 'Vagath the Betrayed' WHERE Entry = 125388;
UPDATE world.creature_template_wdb SET Name1 = 'Ravenous Soulhunter' WHERE Entry = 125389;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 125407;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 125409;
UPDATE world.creature_template_wdb SET Name1 = 'Flickering Argunite' WHERE Entry = 125439;
UPDATE world.creature_template_wdb SET Name1 = 'Tar Eater' WHERE Entry = 125468;
UPDATE world.creature_template_wdb SET Name1 = 'Tar Spitter' WHERE Entry = 125479;
UPDATE world.creature_template_wdb SET Name1 = 'Coagulated Fel' WHERE Entry = 125481;
UPDATE world.creature_template_wdb SET Name1 = 'Skyfin Juvenile' WHERE Entry = 125493;
UPDATE world.creature_template_wdb SET Name1 = 'Overseer Y''Morna' WHERE Entry = 125498;
UPDATE world.creature_template_wdb SET Name1 = 'Warp Stalker Runt' WHERE Entry = 125499;
UPDATE world.creature_template_wdb SET Name1 = 'Nath''raxxan Fleshcarver' WHERE Entry = 125501;
UPDATE world.creature_template_wdb SET Name1 = 'Nath''raxxan Doomshot' WHERE Entry = 125502;
UPDATE world.creature_template_wdb SET Name1 = 'Ravenous Soulhunter' WHERE Entry = 125503;
UPDATE world.creature_template_wdb SET Name1 = 'Heradus', Title = 'Light''s Chosen' WHERE Entry = 125517;
UPDATE world.creature_template_wdb SET Name1 = 'Jost', Title = 'Light''s Chosen' WHERE Entry = 125518;
UPDATE world.creature_template_wdb SET Name1 = 'Divinius', Title = 'Light''s Chosen' WHERE Entry = 125519;
UPDATE world.creature_template_wdb SET Name1 = 'Virtos', Title = 'Light''s Chosen' WHERE Entry = 125520;
UPDATE world.creature_template_wdb SET Name1 = 'Aeqinus', Title = 'Light''s Chosen' WHERE Entry = 125521;
UPDATE world.creature_template_wdb SET Name1 = 'Santus', Title = 'Light''s Chosen' WHERE Entry = 125522;
UPDATE world.creature_template_wdb SET Name1 = 'Exodar Vindicator', NameAlt1 = '' WHERE Entry = 125523;
UPDATE world.creature_template_wdb SET Name1 = 'Lightsworn Anchorite', NameAlt1 = '', Title = 'Hand of Argus' WHERE Entry = 125524;
UPDATE world.creature_template_wdb SET Name1 = 'Durael', Title = 'Repairs' WHERE Entry = 125525;
UPDATE world.creature_template_wdb SET Name1 = 'Jed''hin Master' WHERE Entry = 125532;
UPDATE world.creature_template_wdb SET Name1 = 'Jed''hin Master' WHERE Entry = 125738;
UPDATE world.creature_template_wdb SET Name1 = 'Blacksoul Inquisitor' WHERE Entry = 125779;
UPDATE world.creature_template_wdb SET Name1 = 'Imp Mother Laglath' WHERE Entry = 125820;
UPDATE world.creature_template_wdb SET Name1 = 'Arcane Gorger' WHERE Entry = 125827;
UPDATE world.creature_template_wdb SET Name1 = 'Pygmy Marsuul' WHERE Entry = 125830;
UPDATE world.creature_template_wdb SET Name1 = 'Felcrazed Wyrm' WHERE Entry = 125841;
UPDATE world.creature_template_wdb SET Name1 = 'Exodar Artificer', NameAlt1 = '' WHERE Entry = 125843;
UPDATE world.creature_template_wdb SET Name1 = 'Invasion Point: Aurinor' WHERE Entry = 125849;
UPDATE world.creature_template_wdb SET Name1 = 'Argus Moth' WHERE Entry = 125855;
UPDATE world.creature_template_wdb SET Name1 = 'Anchorite Lysara', Title = 'First Aid Trainer' WHERE Entry = 126022;
UPDATE world.creature_template_wdb SET Name1 = 'Lightsworn Anchorite', Title = 'Hand of Argus' WHERE Entry = 126030;
UPDATE world.creature_template_wdb SET Name1 = 'Fel Geyser' WHERE Entry = 126041;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Artificer', NameAlt1 = '' WHERE Entry = 126042;
UPDATE world.creature_template_wdb SET Name1 = 'Wounded Vindicator', NameAlt1 = '' WHERE Entry = 126043;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Bulwark', NameAlt1 = '' WHERE Entry = 126044;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Dragoon', NameAlt1 = '' WHERE Entry = 126045;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Battlemage', NameAlt1 = '' WHERE Entry = 126046;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Sharpshooter', NameAlt1 = '' WHERE Entry = 126047;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Warpriest', NameAlt1 = '' WHERE Entry = 126048;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Warframe' WHERE Entry = 126049;
UPDATE world.creature_template_wdb SET Name1 = 'Ilthara Darkthorn', Title = 'Illidari Provisioner' WHERE Entry = 126051;
UPDATE world.creature_template_wdb SET Name1 = 'Damaged Warframe' WHERE Entry = 126057;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Brood Mother' WHERE Entry = 126071;
UPDATE world.creature_template_wdb SET Name1 = 'Felspawn Soulstalker' WHERE Entry = 126072;
UPDATE world.creature_template_wdb SET Name1 = 'Felspawn Imp' WHERE Entry = 126073;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Defender' WHERE Entry = 126082;
UPDATE world.creature_template_wdb SET Name1 = 'Burning Fiend' WHERE Entry = 126098;
UPDATE world.creature_template_wdb SET Name1 = 'Venomhide Weaver' WHERE Entry = 126109;
UPDATE world.creature_template_wdb SET Name1 = 'Ven''orn' WHERE Entry = 126115;
UPDATE world.creature_template_wdb SET Name1 = 'Invasion Point: Cen''gar' WHERE Entry = 126120;
UPDATE world.creature_template_wdb SET Name1 = 'Felsiege Infernal' WHERE Entry = 126138;
UPDATE world.creature_template_wdb SET Name1 = 'Ravenous Scavenger' WHERE Entry = 126140;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Warframe' WHERE Entry = 126143;
UPDATE world.creature_template_wdb SET Name1 = 'General Zah''d' WHERE Entry = 126152;
UPDATE world.creature_template_wdb SET Name1 = 'Lead Rider Jerek', Title = 'Stable Master' WHERE Entry = 126160;
UPDATE world.creature_template_wdb SET Name1 = 'Felsworn Myrmidon', NameAlt1 = '' WHERE Entry = 126168;
UPDATE world.creature_template_wdb SET Name1 = 'Tormented Ritualist' WHERE Entry = 126171;
UPDATE world.creature_template_wdb SET Name1 = 'Imprisoned Slave' WHERE Entry = 126173;
UPDATE world.creature_template_wdb SET Name1 = 'Broken Slave' WHERE Entry = 126175;
UPDATE world.creature_template_wdb SET Name1 = 'Exodar Vindicator' WHERE Entry = 126194;
UPDATE world.creature_template_wdb SET Name1 = 'Felfang Basilisk' WHERE Entry = 126197;
UPDATE world.creature_template_wdb SET Name1 = 'Trench Stalker' WHERE Entry = 126198;
UPDATE world.creature_template_wdb SET Name1 = 'Vile Thrasher' WHERE Entry = 126207;
UPDATE world.creature_template_wdb SET Name1 = 'Varga' WHERE Entry = 126208;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar War-Mind', NameAlt1 = '' WHERE Entry = 126233;
UPDATE world.creature_template_wdb SET Name1 = 'Felbound Drudge' WHERE Entry = 126256;
UPDATE world.creature_template_wdb SET Name1 = 'Dreadborne Seer' WHERE Entry = 126284;
UPDATE world.creature_template_wdb SET Name1 = 'Wrathguard Flayer' WHERE Entry = 126335;
UPDATE world.creature_template_wdb SET Name1 = 'Hulking Fiend' WHERE Entry = 126336;
UPDATE world.creature_template_wdb SET Name1 = 'Putrid Engineer' WHERE Entry = 126337;
UPDATE world.creature_template_wdb SET Name1 = 'Fel Shrieker' WHERE Entry = 126341;
UPDATE world.creature_template_wdb SET Name1 = 'Investigate the Ruins of Oronaar' WHERE Entry = 126368;
UPDATE world.creature_template_wdb SET Name1 = 'Artificer Shela''na' WHERE Entry = 126389;
UPDATE world.creature_template_wdb SET Name1 = 'Thelbus Wimblenod' WHERE Entry = 126390;
UPDATE world.creature_template_wdb SET Name1 = 'Bloodsail Corsair', NameAlt1 = '' WHERE Entry = 126399;
UPDATE world.creature_template_wdb SET Name1 = 'Uncrowned Peacekeeper', NameAlt1 = '' WHERE Entry = 126400;
UPDATE world.creature_template_wdb SET Name1 = 'Illidan Stormrage' WHERE Entry = 126408;
UPDATE world.creature_template_wdb SET Name1 = 'Naroua', Title = 'King of the Forest' WHERE Entry = 126419;
UPDATE world.creature_template_wdb SET Name1 = 'Puckish Marsuul' WHERE Entry = 126445;
UPDATE world.creature_template_wdb SET Name1 = 'Wyrmtongue Scrounger' WHERE Entry = 126456;
UPDATE world.creature_template_wdb SET Name1 = 'Felsworn Excavator' WHERE Entry = 126457;
UPDATE world.creature_template_wdb SET Name1 = 'Tormented Krokul' WHERE Entry = 126458;
UPDATE world.creature_template_wdb SET Name1 = 'Excavation Point' WHERE Entry = 126459;
UPDATE world.creature_template_wdb SET Name1 = 'Invasion Point: Bonich' WHERE Entry = 126547;
UPDATE world.creature_template_wdb SET Name1 = 'VFX Bunny' WHERE Entry = 126577;
UPDATE world.creature_template_wdb SET Name1 = 'Prime Naaru' WHERE Entry = 126638;
UPDATE world.creature_template_wdb SET Name1 = 'Nath''raxxan Fleshcarver' WHERE Entry = 126688;
UPDATE world.creature_template_wdb SET Name1 = 'Soultwisted Monstrosity' WHERE Entry = 126815;
UPDATE world.creature_template_wdb SET Name1 = 'Spire of Woe' WHERE Entry = 126853;
UPDATE world.creature_template_wdb SET Name1 = 'Kaara the Pale' WHERE Entry = 126860;
UPDATE world.creature_template_wdb SET Name1 = 'Baruut the Bloodthirsty' WHERE Entry = 126862;
UPDATE world.creature_template_wdb SET Name1 = 'Vigilant Kuro' WHERE Entry = 126866;
UPDATE world.creature_template_wdb SET Name1 = 'Captain Faruq' WHERE Entry = 126869;
UPDATE world.creature_template_wdb SET Name1 = 'Ataxon' WHERE Entry = 126887;
UPDATE world.creature_template_wdb SET Name1 = 'Sorolis the Ill-Fated' WHERE Entry = 126889;
UPDATE world.creature_template_wdb SET Name1 = 'Herald of Chaos' WHERE Entry = 126896;
UPDATE world.creature_template_wdb SET Name1 = 'Sabuul' WHERE Entry = 126898;
UPDATE world.creature_template_wdb SET Name1 = 'Zul''tan the Numerous' WHERE Entry = 126908;
UPDATE world.creature_template_wdb SET Name1 = 'Ruinwalker Stag' WHERE Entry = 126939;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Soulflayer' WHERE Entry = 126941;
UPDATE world.creature_template_wdb SET Name1 = 'Felguard Warden' WHERE Entry = 126942;
UPDATE world.creature_template_wdb SET Name1 = 'Broken Soul' WHERE Entry = 126944;
UPDATE world.creature_template_wdb SET Name1 = 'Imprisoned Krokul' WHERE Entry = 126948;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Beacon' WHERE Entry = 126951;
UPDATE world.creature_template_wdb SET Name1 = 'Ruinwalker Calf' WHERE Entry = 126952;
UPDATE world.creature_template_wdb SET Name1 = 'Restless Denizen' WHERE Entry = 126959;
UPDATE world.creature_template_wdb SET Name1 = 'Restless Denizen' WHERE Entry = 126960;
UPDATE world.creature_template_wdb SET Name1 = 'Forgotten Denizen' WHERE Entry = 126970;
UPDATE world.creature_template_wdb SET Name1 = 'Forgotten Denizen' WHERE Entry = 126971;
UPDATE world.creature_template_wdb SET Name1 = 'Jed''hin Novice' WHERE Entry = 126975;
UPDATE world.creature_template_wdb SET Name1 = 'Jed''hin Adept' WHERE Entry = 126976;
UPDATE world.creature_template_wdb SET Name1 = 'Jed''hin Master' WHERE Entry = 126977;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Citizen' WHERE Entry = 126992;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Citizen' WHERE Entry = 126993;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Citizen', NameAlt1 = '' WHERE Entry = 126994;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Portal Keeper', NameAlt1 = '' WHERE Entry = 126995;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Hound' WHERE Entry = 126996;
UPDATE world.creature_template_wdb SET Name1 = 'Burning Throne Felcaster', NameAlt1 = '' WHERE Entry = 126997;
UPDATE world.creature_template_wdb SET Name1 = 'Burning Throne Executioner', NameAlt1 = '' WHERE Entry = 126998;
UPDATE world.creature_template_wdb SET Name1 = 'Eye of Antorus' WHERE Entry = 126999;
UPDATE world.creature_template_wdb SET Name1 = 'Shadow Fragment' WHERE Entry = 127023;
UPDATE world.creature_template_wdb SET Name1 = 'Nabiru' WHERE Entry = 127037;
UPDATE world.creature_template_wdb SET Name1 = 'Manabound Familiar' WHERE Entry = 127044;
UPDATE world.creature_template_wdb SET Name1 = 'Illidan Stormrage' WHERE Entry = 127051;
UPDATE world.creature_template_wdb SET Name1 = 'Fel' WHERE Entry = 127061;
UPDATE world.creature_template_wdb SET Name1 = 'Artificer Andaara' WHERE Entry = 127083;
UPDATE world.creature_template_wdb SET Name1 = 'All-Seer Xanarian' WHERE Entry = 127096;
UPDATE world.creature_template_wdb SET Name1 = 'Nether Acolyte', NameAlt1 = '' WHERE Entry = 127103;
UPDATE world.creature_template_wdb SET Name1 = 'Wrathguard Overseer' WHERE Entry = 127109;
UPDATE world.creature_template_wdb SET Name1 = 'Ur''zul Fiend' WHERE Entry = 127110;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Soulbinder', NameAlt1 = '' WHERE Entry = 127114;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Bonebreaker' WHERE Entry = 127116;
UPDATE world.creature_template_wdb SET Name1 = 'Vindicator Jaelaana', Title = 'Army of the Light Emissary' WHERE Entry = 127120;
UPDATE world.creature_template_wdb SET Name1 = 'Captured Krokul' WHERE Entry = 127122;
UPDATE world.creature_template_wdb SET Name1 = 'Toraan the Revered', Title = 'Argussian Reach Emissary' WHERE Entry = 127151;
UPDATE world.creature_template_wdb SET Name1 = 'Summoned Ur''zul Fiend' WHERE Entry = 127155;
UPDATE world.creature_template_wdb SET Name1 = 'Krokul Guardian' WHERE Entry = 127163;
UPDATE world.creature_template_wdb SET Name1 = 'Dreadgaze Soulspinner' WHERE Entry = 127164;
UPDATE world.creature_template_wdb SET Name1 = 'Charged Soul Crystal' WHERE Entry = 127171;
UPDATE world.creature_template_wdb SET Name1 = 'Fiendish Imp' WHERE Entry = 127173;
UPDATE world.creature_template_wdb SET Name1 = 'Fel Geyser' WHERE Entry = 127174;
UPDATE world.creature_template_wdb SET Name1 = 'Fel Cannon' WHERE Entry = 127187;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Felslinger', NameAlt1 = '' WHERE Entry = 127188;
UPDATE world.creature_template_wdb SET Name1 = 'Assault Infernal' WHERE Entry = 127189;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Bilescourge' WHERE Entry = 127266;
UPDATE world.creature_template_wdb SET Name1 = 'Defiled Stalker' WHERE Entry = 127270;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Portal' WHERE Entry = 127271;
UPDATE world.creature_template_wdb SET Name1 = 'Ven''orn Broodling' WHERE Entry = 127272;
UPDATE world.creature_template_wdb SET Name1 = 'Antoran Bile Larva' WHERE Entry = 127280;
UPDATE world.creature_template_wdb SET Name1 = 'Houndmaster Kerrax' WHERE Entry = 127288;
UPDATE world.creature_template_wdb SET Name1 = 'Watcher Aival' WHERE Entry = 127291;
UPDATE world.creature_template_wdb SET Name1 = 'Filthy Assistant' WHERE Entry = 127374;
UPDATE world.creature_template_wdb SET Name1 = 'Potion Researcher' WHERE Entry = 127375;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Consul Sculpture' WHERE Entry = 127409;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Wakener Sculpture' WHERE Entry = 127410;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Scholar Sculpture' WHERE Entry = 127411;
UPDATE world.creature_template_wdb SET Name1 = 'Thal''kiel' WHERE Entry = 127429;
UPDATE world.creature_template_wdb SET Name1 = 'Xal''atath' WHERE Entry = 127459;
UPDATE world.creature_template_wdb SET Name1 = 'Light''s Shield' WHERE Entry = 127467;
UPDATE world.creature_template_wdb SET Name1 = 'Scouting Map' WHERE Entry = 127476;
UPDATE world.creature_template_wdb SET Name1 = 'Void Tear' WHERE Entry = 127502;
UPDATE world.creature_template_wdb SET Name1 = 'Adjutant Vortus', Title = 'War Supplies' WHERE Entry = 127518;
UPDATE world.creature_template_wdb SET Name1 = 'Greater Invasion Point: Pit Lord Vilemus' WHERE Entry = 127531;
UPDATE world.creature_template_wdb SET Name1 = 'Felsworn Myrmidon', NameAlt1 = '' WHERE Entry = 127596;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar War-Mind', NameAlt1 = '' WHERE Entry = 127597;
UPDATE world.creature_template_wdb SET Name1 = 'Immortal Netherwalker' WHERE Entry = 127598;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Chaosbringer', NameAlt1 = '' WHERE Entry = 127599;
UPDATE world.creature_template_wdb SET Name1 = 'Shivarra Destroyer' WHERE Entry = 127601;
UPDATE world.creature_template_wdb SET Name1 = 'Demon Hunter', NameAlt1 = '', Title = 'Illidari' WHERE Entry = 127660;
UPDATE world.creature_template_wdb SET Name1 = 'Demon Hunter', NameAlt1 = '', Title = 'Illidari' WHERE Entry = 127661;
UPDATE world.creature_template_wdb SET Name1 = 'Fel Shrieker' WHERE Entry = 127663;
UPDATE world.creature_template_wdb SET Name1 = 'Hadrox' WHERE Entry = 127670;
UPDATE world.creature_template_wdb SET Name1 = 'Radix' WHERE Entry = 127671;
UPDATE world.creature_template_wdb SET Name1 = 'Slave Trap' WHERE Entry = 127722;
UPDATE world.creature_template_wdb SET Name1 = 'Lightsmith Sel''ann', Title = 'Repairs' WHERE Entry = 127751;
UPDATE world.creature_template_wdb SET Name1 = 'Raelaara the Kind', Title = 'Stable Master' WHERE Entry = 127752;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowguard Conjurer' WHERE Entry = 127783;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowguard Voidbender' WHERE Entry = 127784;
UPDATE world.creature_template_wdb SET Name1 = 'Bound Voidlord' WHERE Entry = 127786;
UPDATE world.creature_template_wdb SET Name1 = 'Grand Shadow-Weaver' WHERE Entry = 127791;
UPDATE world.creature_template_wdb SET Name1 = 'Void Discharge' WHERE Entry = 127793;
UPDATE world.creature_template_wdb SET Name1 = 'Umbral War-Adept' WHERE Entry = 127795;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowguard Riftstalker' WHERE Entry = 127796;
UPDATE world.creature_template_wdb SET Name1 = 'Shadowguard Champion' WHERE Entry = 127797;
UPDATE world.creature_template_wdb SET Name1 = 'Void Flayer' WHERE Entry = 127798;
UPDATE world.creature_template_wdb SET Name1 = 'Everburning Doombringer' WHERE Entry = 127811;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Warframe' WHERE Entry = 127823;
UPDATE world.creature_template_wdb SET Name1 = 'Na''nuu', Title = 'Blacksmith' WHERE Entry = 127920;
UPDATE world.creature_template_wdb SET Name1 = 'Felforge Salvager' WHERE Entry = 127942;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Fighter' WHERE Entry = 127945;
UPDATE world.creature_template_wdb SET Name1 = 'Void Terror' WHERE Entry = 128046;
UPDATE world.creature_template_wdb SET Name1 = 'Eye of Observation' WHERE Entry = 128068;
UPDATE world.creature_template_wdb SET Name1 = 'Orix the All-Seer' WHERE Entry = 128134;
UPDATE world.creature_template_wdb SET Name1 = 'Fallen Soldier', NameAlt1 = '' WHERE Entry = 128135;
UPDATE world.creature_template_wdb SET Name1 = 'All-Seer''s Focus' WHERE Entry = 128151;
UPDATE world.creature_template_wdb SET Name1 = 'Augari Security Spell' WHERE Entry = 128176;
UPDATE world.creature_template_wdb SET Name1 = 'Cultivated Argunite' WHERE Entry = 128191;
UPDATE world.creature_template_wdb SET Name1 = 'Forgotten Crystal Tender' WHERE Entry = 128192;
UPDATE world.creature_template_wdb SET Name1 = 'Domesticated Marsuul' WHERE Entry = 128193;
UPDATE world.creature_template_wdb SET Name1 = 'Domesticated Skyfin' WHERE Entry = 128194;
UPDATE world.creature_template_wdb SET Name1 = 'Domesticated Chitinbuk' WHERE Entry = 128196;
UPDATE world.creature_template_wdb SET Name1 = 'Crafter Y''selfa', Title = 'Jewelry Vendor' WHERE Entry = 128198;
UPDATE world.creature_template_wdb SET Name1 = 'Kuraam', Title = 'Tournament Vendor' WHERE Entry = 128199;
UPDATE world.creature_template_wdb SET Name1 = 'Tournament Groundskeeper', NameAlt1 = '' WHERE Entry = 128203;
UPDATE world.creature_template_wdb SET Name1 = 'Mender Askara' WHERE Entry = 128208;
UPDATE world.creature_template_wdb SET Name1 = 'Relic Keeper Calindris' WHERE Entry = 128210;
UPDATE world.creature_template_wdb SET Name1 = 'Councilor Hataaru' WHERE Entry = 128211;
UPDATE world.creature_template_wdb SET Name1 = 'Councilor Larohir' WHERE Entry = 128212;
UPDATE world.creature_template_wdb SET Name1 = 'Naielle' WHERE Entry = 128213;
UPDATE world.creature_template_wdb SET Name1 = 'Councilor Othaar' WHERE Entry = 128214;
UPDATE world.creature_template_wdb SET Name1 = 'Akama' WHERE Entry = 128215;
UPDATE world.creature_template_wdb SET Name1 = 'Silgryn' WHERE Entry = 128241;
UPDATE world.creature_template_wdb SET Name1 = 'Kal', Title = 'Silgryn''s Companion' WHERE Entry = 128242;
UPDATE world.creature_template_wdb SET Name1 = 'Aethas Sunreaver' WHERE Entry = 128243;
UPDATE world.creature_template_wdb SET Name1 = 'Lady Liadrin', Title = 'Blood Knight Matriarch' WHERE Entry = 128244;
UPDATE world.creature_template_wdb SET Name1 = 'Archmage Khadgar' WHERE Entry = 128245;
UPDATE world.creature_template_wdb SET Name1 = 'Hakmud of Argus' WHERE Entry = 128288;
UPDATE world.creature_template_wdb SET Name1 = 'Damaged Argus Construct' WHERE Entry = 128357;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Dragoon' WHERE Entry = 128364;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Dragoon' WHERE Entry = 128365;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Dragoon' WHERE Entry = 128366;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Dragoon' WHERE Entry = 128367;
UPDATE world.creature_template_wdb SET Name1 = 'Captain Fareeya', Title = 'The Crescent Glaive' WHERE Entry = 128370;
UPDATE world.creature_template_wdb SET Name1 = 'Beast' WHERE Entry = 128752;
UPDATE world.creature_template_wdb SET Name1 = 'Maras', Title = 'Primal Sargerite Trader' WHERE Entry = 129674;
UPDATE world.creature_template_wdb SET Name1 = 'Elusive Chitinbuk' WHERE Entry = 130935;
UPDATE world.creature_template_wdb SET Name1 = 'Albino Umbralfin' WHERE Entry = 130937;
UPDATE world.creature_template_wdb SET Name1 = 'Ancient Duskcloak' WHERE Entry = 130943;
UPDATE world.creature_template_wdb SET Name1 = 'Manasaber' WHERE Entry = 131069;
UPDATE world.creature_template_wdb SET Name1 = 'Arluelle' WHERE Entry = 220085;
UPDATE world.creature_template_wdb SET Name1 = 'Arcanist Valtrois' WHERE Entry = 220086;
UPDATE world.creature_template_wdb SET Name1 = 'Alleria Windrunner' WHERE Entry = 220095;
UPDATE world.creature_template_wdb SET Name1 = 'Terokk' WHERE Entry = 231018;
UPDATE world.creature_template_wdb SET Name1 = 'Archmage Khadgar' WHERE Entry = 950116;

-- No English source (custom or unused alpha NPCs): translated
UPDATE world.creature_template_wdb SET Name1 = 'Stormwind Knight', NameAlt1 = '' WHERE Entry = 94628;
UPDATE world.creature_template_wdb SET Name1 = 'Stormwind Knight', NameAlt1 = '' WHERE Entry = 94631;
UPDATE world.creature_template_wdb SET Name1 = 'King Ymiron' WHERE Entry = 97082;
UPDATE world.creature_template_wdb SET Name1 = 'Futhark', Title = 'Great Runecarver' WHERE Entry = 97611;
UPDATE world.creature_template_wdb SET Name1 = 'Dread Infector' WHERE Entry = 104469;
UPDATE world.creature_template_wdb SET Name1 = 'Dread Manipulator' WHERE Entry = 104470;
UPDATE world.creature_template_wdb SET Name1 = 'Dread Will-Breaker' WHERE Entry = 104471;
UPDATE world.creature_template_wdb SET Name1 = 'Dread Minion' WHERE Entry = 104472;
UPDATE world.creature_template_wdb SET Name1 = 'Dread Lieutenant' WHERE Entry = 104473;
UPDATE world.creature_template_wdb SET Name1 = 'Orgrimmar Grunt' WHERE Entry = 104616;
UPDATE world.creature_template_wdb SET Name1 = 'Orgrimmar Grunt' WHERE Entry = 104617;
UPDATE world.creature_template_wdb SET Name1 = 'Corrupted Bloodfang' WHERE Entry = 104697;
UPDATE world.creature_template_wdb SET Name1 = 'Voice from the Portal' WHERE Entry = 200407;
UPDATE world.creature_template_wdb SET Name1 = 'Spawn of Chaos' WHERE Entry = 200450;
UPDATE world.creature_template_wdb SET Name1 = 'Huan-Di', Title = 'Mysterious Wanderer' WHERE Entry = 200463;
UPDATE world.creature_template_wdb SET Name1 = 'Heart of Y''Shaarj' WHERE Entry = 200464;
UPDATE world.creature_template_wdb SET Name1 = 'Sha of Chaos' WHERE Entry = 200465;
UPDATE world.creature_template_wdb SET Name1 = 'Shop Item Refunds' WHERE Entry = 220011;
UPDATE world.creature_template_wdb SET Name1 = 'Character Transfer', Title = '' WHERE Entry = 220020;   -- title was another server's name (uwow.biz)
UPDATE world.creature_template_wdb SET Name1 = 'Void Elf (M)' WHERE Entry = 230009;
UPDATE world.creature_template_wdb SET Name1 = 'Void Elf (F)' WHERE Entry = 230010;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Draenei (M)' WHERE Entry = 230011;
UPDATE world.creature_template_wdb SET Name1 = 'Lightforged Draenei (F)' WHERE Entry = 230012;
UPDATE world.creature_template_wdb SET Name1 = 'Nightborne (M)' WHERE Entry = 230013;
UPDATE world.creature_template_wdb SET Name1 = 'Nightborne (F)' WHERE Entry = 230014;
UPDATE world.creature_template_wdb SET Name1 = 'Highmountain Tauren (M)' WHERE Entry = 230015;
UPDATE world.creature_template_wdb SET Name1 = 'Highmountain Tauren (F)' WHERE Entry = 230016;
UPDATE world.creature_template_wdb SET Name1 = 'Fashion Mannequin' WHERE Entry = 230017;
UPDATE world.creature_template_wdb SET Name1 = 'Lava Flow' WHERE Entry = 231023;
UPDATE world.creature_template_wdb SET Name1 = 'Temple of Five Dawns Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400001;
UPDATE world.creature_template_wdb SET Name1 = 'Tirisgarde Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400002;
UPDATE world.creature_template_wdb SET Name1 = 'Illidari Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400003;
UPDATE world.creature_template_wdb SET Name1 = 'Trueshot Lodge Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400004;
UPDATE world.creature_template_wdb SET Name1 = 'Dreadscar Rift Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400005;
UPDATE world.creature_template_wdb SET Name1 = 'Skyhold Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400006;
UPDATE world.creature_template_wdb SET Name1 = 'Dreamgrove Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400007;
UPDATE world.creature_template_wdb SET Name1 = 'Sanctum of Light Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400008;
UPDATE world.creature_template_wdb SET Name1 = 'Keeper of the Heart of Azeroth', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400009;
UPDATE world.creature_template_wdb SET Name1 = 'Netherlight Temple Acolyte', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400010;
UPDATE world.creature_template_wdb SET Name1 = 'Acherus Attendant', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400011;
UPDATE world.creature_template_wdb SET Name1 = 'Hall of Shadows Attendant', TitleAlt = 'Class Hall Quest Guide' WHERE Entry = 400012;
UPDATE world.creature_template_wdb SET Name1 = 'Rift' WHERE Entry = 542003;
UPDATE world.creature_template_wdb SET Name1 = 'Rift' WHERE Entry = 542006;
UPDATE world.creature_template_wdb SET Name1 = 'Eredar Conqueror' WHERE Entry = 542100;
UPDATE world.creature_template_wdb SET Name1 = 'Scarwing Ravager' WHERE Entry = 542101;
UPDATE world.creature_template_wdb SET Name1 = 'Vilefiend' WHERE Entry = 542102;
UPDATE world.creature_template_wdb SET Name1 = 'Banelord' WHERE Entry = 542103;
UPDATE world.creature_template_wdb SET Name1 = 'Abyssal Annihilator' WHERE Entry = 542104;
UPDATE world.creature_template_wdb SET Name1 = 'Herald of War' WHERE Entry = 542105;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Brute' WHERE Entry = 542106;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Warship' WHERE Entry = 542107;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Warship' WHERE Entry = 542108;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Warship' WHERE Entry = 542109;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Warship' WHERE Entry = 542110;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Commander' WHERE Entry = 542111;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Commander' WHERE Entry = 542112;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Harbinger' WHERE Entry = 542118;
UPDATE world.creature_template_wdb SET Name1 = 'Legion Berserker' WHERE Entry = 542119;
UPDATE world.creature_template_wdb SET Name1 = 'Portal' WHERE Entry = 542120;
UPDATE world.creature_template_wdb SET Name1 = 'Portal' WHERE Entry = 542121;
UPDATE world.creature_template_wdb SET Name1 = 'Portal' WHERE Entry = 542122;
UPDATE world.creature_template_wdb SET Name1 = 'Portal' WHERE Entry = 542123;
UPDATE world.creature_template_wdb SET Name1 = 'Portal' WHERE Entry = 542124;
UPDATE world.creature_template_wdb SET Name1 = 'Portal' WHERE Entry = 542125;
UPDATE world.creature_template_wdb SET Name1 = 'Catapult' WHERE Entry = 542126;
UPDATE world.creature_template_wdb SET Name1 = 'Spirit' WHERE Entry = 542129;
UPDATE world.creature_template_wdb SET Name1 = 'Stromgarde Defender' WHERE Entry = 542130;
UPDATE world.creature_template_wdb SET Name1 = 'Stromgarde Soldier' WHERE Entry = 542131;
UPDATE world.creature_template_wdb SET Name1 = 'Syndicate Rogue' WHERE Entry = 542132;
UPDATE world.creature_template_wdb SET Name1 = 'Invading Warrior' WHERE Entry = 542133;
UPDATE world.creature_template_wdb SET Name1 = 'Invading Mage' WHERE Entry = 542134;
UPDATE world.creature_template_wdb SET Name1 = 'Grapple Point' WHERE Entry = 542135;
UPDATE world.creature_template_wdb SET Name1 = 'Defensive Trap' WHERE Entry = 542136;
UPDATE world.creature_template_wdb SET Name1 = 'Rift' WHERE Entry = 542137;
UPDATE world.creature_template_wdb SET Name1 = 'Ennera, Keeper of Portals' WHERE Entry = 542138;
UPDATE world.creature_template_wdb SET Name1 = 'Exit' WHERE Entry = 542139;
UPDATE world.creature_template_wdb SET Name1 = 'Table' WHERE Entry = 542140;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Grunt' WHERE Entry = 542142;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Spearman' WHERE Entry = 542143;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Rogue' WHERE Entry = 542144;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Sorcerer' WHERE Entry = 542145;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Grunt' WHERE Entry = 542146;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Spearman' WHERE Entry = 542147;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Rogue' WHERE Entry = 542148;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Sorcerer' WHERE Entry = 542149;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Guard' WHERE Entry = 542150;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Rogue' WHERE Entry = 542151;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Warrior' WHERE Entry = 542152;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Mage' WHERE Entry = 542153;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Guard' WHERE Entry = 542154;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Rogue' WHERE Entry = 542155;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Warrior' WHERE Entry = 542156;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Mage' WHERE Entry = 542157;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Officer' WHERE Entry = 542159;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Officer' WHERE Entry = 542160;
UPDATE world.creature_template_wdb SET Name1 = 'Gryphon Rider' WHERE Entry = 542161;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Wind Rider' WHERE Entry = 542162;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Fighter' WHERE Entry = 542163;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Fighter' WHERE Entry = 542164;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Flag Bearer' WHERE Entry = 542165;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Flag Bearer' WHERE Entry = 542166;
UPDATE world.creature_template_wdb SET Name1 = 'Wounded Horde Fighter' WHERE Entry = 542167;
UPDATE world.creature_template_wdb SET Name1 = 'Horde Healer' WHERE Entry = 542168;
UPDATE world.creature_template_wdb SET Name1 = 'Wounded Alliance Fighter' WHERE Entry = 542169;
UPDATE world.creature_template_wdb SET Name1 = 'Alliance Healer' WHERE Entry = 542170;
UPDATE world.creature_template_wdb SET Name1 = 'Wind Rider' WHERE Entry = 542171;
UPDATE world.creature_template_wdb SET Name1 = 'Gryphon' WHERE Entry = 542172;
UPDATE world.creature_template_wdb SET Name1 = 'Wind Rider' WHERE Entry = 542173;
UPDATE world.creature_template_wdb SET Name1 = 'Gryphon' WHERE Entry = 542174;
UPDATE world.creature_template_wdb SET Name1 = 'Protective Dome' WHERE Entry = 542175;
UPDATE world.creature_template_wdb SET Name1 = 'Protective Dome' WHERE Entry = 542176;
UPDATE world.creature_template_wdb SET Name1 = 'Wounded Horde Fighter' WHERE Entry = 542177;
UPDATE world.creature_template_wdb SET Name1 = 'Wounded Alliance Fighter' WHERE Entry = 542178;
UPDATE world.creature_template_wdb SET Name1 = 'Power-Up' WHERE Entry = 542179;
UPDATE world.creature_template_wdb SET Name1 = 'Hoarus' WHERE Entry = 600000;
UPDATE world.creature_template_wdb SET Name1 = 'Ice Tomb' WHERE Entry = 600002;
UPDATE world.creature_template_wdb SET Name1 = 'Frost Spike' WHERE Entry = 600004;
UPDATE world.creature_template_wdb SET Name1 = 'Ice Elemental' WHERE Entry = 600005;
UPDATE world.creature_template_wdb SET Name1 = 'Grid' WHERE Entry = 600006;
UPDATE world.creature_template_wdb SET Name1 = 'Portal' WHERE Entry = 600007;
UPDATE world.creature_template_wdb SET Name1 = 'Master Alchemist', Title = 'Specialization Training and Reset' WHERE Entry = 600012;
UPDATE world.creature_template_wdb SET Name1 = 'The Black Prince' WHERE Entry = 600016;
UPDATE world.creature_template_wdb SET Name1 = 'Felhound' WHERE Entry = 600017;
UPDATE world.creature_template_wdb SET Name1 = 'Strike Target' WHERE Entry = 600018;
UPDATE world.creature_template_wdb SET Name1 = 'Air Current' WHERE Entry = 600052;
UPDATE world.creature_template_wdb SET Name1 = 'Cage Opener' WHERE Entry = 950000;
