-- Undo fix_playerchoice_english.sql (apply with --default-character-set=utf8mb4)
UPDATE world.playerchoice_response SET `Answer`='Истребление' WHERE ChoiceId=231 AND ResponseId=478;
UPDATE world.playerchoice_response SET `Answer`='Месть' WHERE ChoiceId=231 AND ResponseId=479;
UPDATE world.playerchoice_response SET `Header`='Ликвидация' WHERE ChoiceId=262 AND ResponseId=568;
UPDATE world.playerchoice_response SET `Answer`='Выбрать' WHERE ChoiceId=262 AND ResponseId=568;
UPDATE world.playerchoice_response SET `Description`='Убийцы Королей – кинжалы Гароны, которыми она убивала неугодных Гул\'дану. Они отравляют жертву ядом, не оставляющим следов, поэтому когда Убийцы Королей решают чью-то судьбу, это невозможно доказать.\n\nДушевные муки вынудили Гарону спрятать кинжалы, но позже она вернулась за ними, чтобы одолеть опасных служителей Легиона.\n\nМы должны ее найти.' WHERE ChoiceId=262 AND ResponseId=568;
UPDATE world.playerchoice_response SET `Header`='Головорез' WHERE ChoiceId=262 AND ResponseId=569;
UPDATE world.playerchoice_response SET `Answer`='Выбрать' WHERE ChoiceId=262 AND ResponseId=569;
UPDATE world.playerchoice_response SET `Description`='Жуткий адмирал Элиза – гроза Южных морей. Ее проклятые клинки нагоняют ужас на многих.\n\nМы узнали, что ее корабль бросил якорь у берегов Азсуны на Расколотых островах. Если поспешить, то можно заполучить ее клинки.' WHERE ChoiceId=262 AND ResponseId=569;
UPDATE world.playerchoice_response SET `Header`='Скрытность' WHERE ChoiceId=262 AND ResponseId=570;
UPDATE world.playerchoice_response SET `Answer`='Выбрать' WHERE ChoiceId=262 AND ResponseId=570;
UPDATE world.playerchoice_response SET `Description`='Акаари Кровавая Тьма – непревзойденная эредарская убийца, предмет особой гордости Легиона. Ее кинжалы способны искажать пространство, скрывая своего владельца в тени.\n\nУ нас есть данные разведки, указывающие, где она находится в настоящее время. Пора нанести удар.' WHERE ChoiceId=262 AND ResponseId=570;
UPDATE world.playerchoice_response SET `Header`='Правосудие Света' WHERE ChoiceId=317 AND ResponseId=771;
UPDATE world.playerchoice_response SET `Answer`='Выбрать' WHERE ChoiceId=317 AND ResponseId=771;
UPDATE world.playerchoice_response SET `Description`='Выбрав эту способность, вы сможете указывать цели для обстрела из "Правосудия Света", главного орудия "Виндикара". Действует только на Аргусе.' WHERE ChoiceId=317 AND ResponseId=771;
UPDATE world.playerchoice_response SET `Header`='Оскверненное сердце' WHERE ChoiceId=317 AND ResponseId=775;
UPDATE world.playerchoice_response SET `Answer`='Выбрать' WHERE ChoiceId=317 AND ResponseId=775;
UPDATE world.playerchoice_response SET `Description`='Выбрав оскверненное сердце Аргуса, вы сможете исцеляться вне боя, а также возвращаться к жизни после получения смертельного урона.' WHERE ChoiceId=317 AND ResponseId=775;
UPDATE world.playerchoice_response SET `Answer`='Активировать' WHERE ChoiceId=317 AND ResponseId=782;
UPDATE world.playerchoice_response SET `Description`='Активируйте ядро матрицы и выберите "Правосудие Света" – главное орудие "Виндикара" – в качестве способности для использования на Аргусе.' WHERE ChoiceId=317 AND ResponseId=782;
UPDATE world.playerchoice SET Question='Какую постройку мы возведем на аванпосте?' WHERE ChoiceId=52;
UPDATE world.playerchoice SET Question='Какую постройку мы возведем на аванпосте?' WHERE ChoiceId=53;
UPDATE world.playerchoice SET Question='Какую постройку мы возведем на аванпосте?' WHERE ChoiceId=54;
UPDATE world.playerchoice SET Question='Какую постройку мы возведем на аванпосте?' WHERE ChoiceId=56;
UPDATE world.playerchoice SET Question='Какую постройку мы возведем на аванпосте?' WHERE ChoiceId=57;
UPDATE world.playerchoice SET Question='Выбор военной операции' WHERE ChoiceId=70;
UPDATE world.playerchoice SET Question='Выбор военной операции' WHERE ChoiceId=128;
UPDATE world.playerchoice SET Question='Выбор военной операции' WHERE ChoiceId=174;
UPDATE world.playerchoice SET Question='Поисками какого оружия нам следует заняться в первую очередь?' WHERE ChoiceId=262;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски второго артефактного оружия?' WHERE ChoiceId=270;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски второго артефактного оружия?' WHERE ChoiceId=273;
UPDATE world.playerchoice SET Question='Какое оружие нам следует искать следующим?' WHERE ChoiceId=274;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски второго артефактного оружия?' WHERE ChoiceId=275;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски второго артефактного оружия?' WHERE ChoiceId=277;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски второго артефактного оружия?' WHERE ChoiceId=279;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски второго артефактного оружия?' WHERE ChoiceId=280;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски второго артефактного оружия?' WHERE ChoiceId=282;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски другого артефактного оружия?' WHERE ChoiceId=284;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски другого артефактного оружия?' WHERE ChoiceId=287;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски другого артефактного оружия?' WHERE ChoiceId=288;
UPDATE world.playerchoice SET Question='Вы хотите начать поиски артефактного оружия?' WHERE ChoiceId=292;
UPDATE world.playerchoice SET Question='Выберите способность "Виндикара" для использования на Аргусе.' WHERE ChoiceId=317;
