-- #155 (help-helper, Claude 2026-10-02): undo of fix_quest_texts_ru_18.sql. Restores the exact Russian base text of
-- 37972, 41289, 41325, 41334, 41507, 41547, 41577, 47040, 90000-90007, the 41289 objective and the 90005 request text,
-- guarded on the English values. Apply with --default-character-set=utf8mb4.
SET NAMES utf8mb4;
UPDATE world.quest_template SET LogTitle = 'Неактивные битвы питомцев' WHERE ID = 37972 AND LogTitle = 'Pet Battles Not Active';
UPDATE world.quest_template SET LogTitle = 'Цветущий айтрил' WHERE ID = 41289 AND LogTitle = 'Flourishing Aethril';
UPDATE world.quest_template SET LogTitle = 'Скользкая шкура тюленя' WHERE ID = 41325 AND LogTitle = 'Slick Seal Hide';
UPDATE world.quest_template SET LogTitle = 'Пахнущая мускусом медвежья шкура' WHERE ID = 41334 AND LogTitle = 'Musky Bear Hide';
UPDATE world.quest_template SET LogTitle = 'Василиски силового камня' WHERE ID = 41507 AND LogTitle = 'Leystone Basilisks';
UPDATE world.quest_template SET LogTitle = 'Пучок фьярнскаггла' WHERE ID = 41547 AND LogTitle = 'Fjarnskaggl Cluster';
UPDATE world.quest_template SET LogTitle = 'Чешуйка с лапы руха' WHERE ID = 41577 AND LogTitle = 'Roc Talon Scale';
UPDATE world.quest_template SET LogTitle = 'Печать судьбы' WHERE ID = 47040 AND LogTitle = 'Fate Sealed';
UPDATE world.quest_template SET LogTitle = 'Праздника не будет!', LogDescription = 'Найдите Альбонда в Долине Призрачной Луны.', QuestDescription = 'В наших краях произошла большая беда. Новый год был похищен! И неизвестно как это повлияет на судьбу всего Азерота! \r\n$c, если ты $gсогласен:согласна; нам помочь, помочь всему Азероту, тебе предстоит выяснить, кто похитил праздник. \r\n\r\nПрошел слух о том, что маг по имени Альбонд сейчас находится в Долине Призрачной Луны, что в Запределье.\r\nАльбонд – потомок великого алхимика Парнети, который и создал новый год несколько тысяч лет назад, я думаю, он поможет нам.\r\n\r\nБудь осторожнее с ним, я слышал, что он немного странный.', AreaDescription = 'Альбонд найден' WHERE ID = 90000 AND LogTitle = 'There Will Be No Holiday!';
UPDATE world.quest_template SET LogTitle = 'История Нового года', LogDescription = 'Выслушайте историю Альбонда.', QuestDescription = 'Ага, снова ты. Я знал, что прихвостни дедушки зимы пришлют кого-то ко мне, ибо я единственный кто может что-то знать об этом.\r\nДавай-ка я поведаю тебе кое о чем?', AreaDescription = 'Выслушайте историю старого мага' WHERE ID = 90001 AND LogTitle = 'The Story of the New Year';
UPDATE world.quest_template SET LogTitle = 'Материалы', LogDescription = 'Принесите Альбонду ингредиенты.', QuestDescription = 'Для создания прибора потребуются несколько ингредиентов.\r\nСердце детеныша дракона Нексуса, который находится в Борейской Тундре, 6 горсток первого снега из Зимних Ключей, и немного магической воды из озера Элуне’ара, ее можно раздобыть, хорошо попросив у Хранителя Ремула.', AreaDescription = 'Вернитесь к Альбонду с ингредиентами.' WHERE ID = 90002 AND LogTitle = 'Materials';
UPDATE world.quest_template SET LogTitle = 'Забытая деталь', LogDescription = 'Найди гоблина Кальтаса и раздобудь у него камень тернистого леса.', QuestDescription = 'Ох, моя память совсем уже плоха. Я забыл, о еще одной детали для нашего чудного прибора. Камень тернистого леса! \r\n\r\nЕсть один гоблин, ошивается он в болотах печали. У него есть то, что нам нужно… камень тернистого леса, обладающий древней магией, без него нам не обойтись. Гоблина зовут Кальтас, я думаю, ты его быстро найдешь.', QuestCompletionLog = 'Вернитесь к Альбонду' WHERE ID = 90003 AND LogTitle = 'The Forgotten Part';
UPDATE world.quest_template SET LogTitle = 'И у преступников бывает праздник', LogDescription = 'Принесите гоблину необходимые ему вещи.', QuestDescription = 'Камень тернистого леса, говоришь? Да, он у меня есть, но я тебе его так просто не отдам. \r\n\r\nДавно хотел попробовать ледяное молоко и имбирное печенье, но времени у меня сейчас совсем нет. Кручусь целыми днями как белка в колесе с этими заказными убийствами и прочими черными делами. \r\n\r\nКстати, на днях у меня накрылся прицел на моей винтовке, а куда убийце без оптики? Я слышал, «Кориевый прицел» отличная модель, так что придется тебе найти для меня и его, и я отдам тебе этот камень.', QuestCompletionLog = 'Вернитесь к Кальтасу' WHERE ID = 90004 AND LogTitle = 'Even Criminals Have Holidays';
UPDATE world.quest_template SET LogTitle = 'Всплеск энергии обнаружен!', LogDescription = 'Отправляйтесь в Прибамбасск и расспросите хозяина таверны.', QuestDescription = 'Компас озарил голубым сиянием небо. Картинка была очень четкой, словно нарисованная. Я вижу причал, дома таверну. Это не что иное как Прибамбасск. Надо отправиться туда, и расспросить местных. Я думаю, хозяин таверны что-то должен знать.', AreaDescription = 'Хозяин таверны расспрошен', QuestCompletionLog = 'Поговорите с Дионисом' WHERE ID = 90005 AND LogTitle = 'Energy Surge Detected!';
UPDATE world.quest_template SET LogTitle = 'На поиски Шакро', LogDescription = 'Шакро находиться где-то в Аукиндоне, найдите его!', QuestDescription = 'Заходил тут вчера тот, кого ты ищешь, зовут его Шакро. Общается он с бесами или демонами, в общем, то я точно не знаю. Он хотел, что бы я помог ему в поиске наемников… говорил, что он в какой-то опасности. Я ему, конечно, отказал, ведь уже давно отошел от всех черных делишек. \r\nОн оставил мне подсказку как его можно найти. Сказал, что будет где-то в Аукиндоне, где именно умолчал.', QuestCompletionLog = 'Отнесите письмо Альбонду' WHERE ID = 90006 AND LogTitle = 'In Search of Shakro';
UPDATE world.quest_template SET LogTitle = 'Спасение нового года', LogDescription = 'Отправляйся в Ревущий фьорд и спаси новый год!', QuestDescription = 'Очень странно. В письме говориться о том, что «Зиме» отдан приказ уничтожить артефакт, так как у демонов в этом мире не хватило сил уничтожить его самим. \r\nНо как это возможно? «Зима» предал дух нового года? Что-то здесь не так, быть может, его разум захвачен врагом?\r\n\r\nАртефакт можно уничтожить только в том месте, там, где он был создан. В горах Ревущего фьорда! Поспешим!', AreaDescription = 'Новый год спасен', QuestCompletionLog = 'Получите подарок' WHERE ID = 90007 AND LogTitle = 'Saving the New Year';
UPDATE world.quest_objectives SET Description = 'Цветущий айтрил' WHERE ID = 282167 AND QuestID = 41289 AND Description = 'Flourishing Aethril';
UPDATE world.quest_request_items SET CompletionText = 'Этот компас когда-то принадлежал моему прадеду, я думаю будет справедливо, если ты отдашь его мне, а  я расскажу тебе то, что тебя интересует.' WHERE ID = 90005 AND CompletionText = 'This compass once belonged to my great-grandfather. I think it is only fair that you give it to me, and I will tell you what you want to know.';
