/*
 * Party bots (owner request 2026-09-28, #65), phase 1: a character of another (offline) account logs in without a
 * client, joins its leader's group, follows the leader across maps and helps with auto attacks.
 * Spells per spec (tank / healer / damage rotations) come in the next phases.
 *
 * Built on the idea of normalzero/LegionPlayerBot (PlayerBotSession): a WorldSession without a socket whose login,
 * teleports and loading screens the server acknowledges itself.
 */
#ifndef PARTYBOT_H
#define PARTYBOT_H

#include "WorldSession.h"
#include <atomic>
#include "UnitAI.h"
#include "MoveSplineInitArgs.h"

struct ChrSpecializationEntry;

class PartyBotSession : public WorldSession
{
public:
    // questMaxLevel > 0: a quest-test bot (QuestBot.cpp): alone, no group, plays quests up to that level
    // dungeonRole (lfg::LfgRoles) > 0: a dungeon-test bot (DungeonRun.cpp); leaderGuid = its run's tank (the tank: itself)
    PartyBotSession(uint32 accountId, std::string&& accountName, ObjectGuid botGuid, ObjectGuid leaderGuid, uint8 questMaxLevel = 0, uint8 dungeonRole = 0);

    bool IsBotSession() const override { return true; }
    bool BotCanBeRemoved() const override { return _done; }
    bool Update(uint32 diff, Map* map = nullptr) override;

    ObjectGuid GetBotGuid() const { return _botGuid; }
    ObjectGuid GetLeaderGuid() const { return _leaderGuid; }
    void Dismiss();                     // leave the group and log out (the bot's own thread only)
    void RequestDismiss() { _dismissRequested = true; }  // any thread (.partybot remove): the bot's session update dismisses
    bool IsDismissed() const { return _dismissed || _dismissRequested; }
    bool IsQuestTest() const { return _questMaxLevel != 0; }
    bool IsDungeonBot() const { return _dungeonRole != 0; }

private:
    void Setup(Player* bot);
    void FirstLoginSetup(Player* bot, uint32 specId, bool levelBot);
    void FillArtifacts(Player* bot);
    void AckTeleports(Player* bot);
    void DungeonSetup(Player* bot);                 // DungeonRun.cpp: the AI (the tank's comes in the dungeon)
    void DungeonUpdate(Player* bot, uint32 diff);   // DungeonRun.cpp: the Dungeon Finder answers, the run's steps (tank)

    ObjectGuid _botGuid;
    ObjectGuid _leaderGuid;
    bool _loginStarted = false;
    bool _setupDone = false;
    bool _dismissed = false;
    std::atomic<bool> _dismissRequested{ false };
    bool _done = false;
    uint32 _leaderGoneTimer = 0;
    uint32 _groupGoneTimer = 0;         // not in the leader's group (kicked)
    uint8 _questMaxLevel = 0;
    uint32 _deadTimer = 0;              // quest test: dead this long
    uint8 _talentLevel = 0;             // #140 A: the level the bot's talents were learned for (0: not seen yet)
    uint8 _dungeonRole = 0;
    uint32 _answerTimer = 0;            // dungeon bot: until the next Dungeon Finder answer
};

// phase 2: one row of world.partybot_spells (generated by tools/partybot/gen_partybot_spells.py)
enum class PartyBotSpellType : uint8
{
    Damage, Dot, Execute, Finisher, Buff, Cooldown, Aoe, Heal, Hot, AoeHeal, SelfHeal, Taunt, Pet
};

struct PartyBotSpell
{
    uint32 Spell;
    PartyBotSpellType Type;
    int32 Param;
    uint32 Aura;                        // aura to look for (dot/buff/hot); 0 = the spell itself
};

class PartyBotAI : public PlayerAI
{
public:
    PartyBotAI(Player* bot, ObjectGuid leaderGuid, uint8 slot) : PlayerAI(bot), _leaderGuid(leaderGuid), _slot(slot) { }

    void UpdateAI(uint32 diff) override;

protected:                              // the quest-test bot (QuestBotAI) fights with the same rotation
    void FollowLeader(Player* leader);
    Unit* PickTarget(Player* leader) const;
    uint32 EnemiesNear(Unit* center, float range) const;
    bool CastRotation(Unit* target);                       // true when a spell was cast
    bool TryCast(PartyBotSpell const& entry, Unit* target);
    Unit* LowestGroupMember(int32 belowPct, uint32 withoutAura, bool inSightOnly = true) const;
    bool InSight(Unit* unit, float range) const;
    bool Approach(Unit* unit);                             // false: gave up (no path, or too long)
    void StandStill();
    void PetAttack(Unit* target);                         // the bot's pet attacks its target (pets start passive)
    bool WalkTo(Position const& pos);                     // along the navmesh corridor's corners; false: no path
    void PositionRanged(Unit* target, Player* leader);
    void PositionHealer(Player* leader);
    uint32 GroupMembersBelow(int32 pct) const;
    Unit* TauntTarget() const;
    bool IsRanged() const;

    ObjectGuid _leaderGuid;
    uint8 _slot;                        // position around the leader
    uint32 _checkTimer = 0;
    ObjectGuid _approachGuid;           // who the bot is walking to (positioning)
    uint8 _approachTicks = 0;           // AI ticks spent walking to an unseen target
    Movement::PointsArray _walkRoute;   // WalkTo: the corridor corners of the last walk (the dungeon watch export shows the tank's)
    SpellCastResult _castResult = SPELL_FAILED_DONT_REPORT;    // the last TryCast's CastSpell result (DONT_REPORT: not tried)
};

// ---- C (DungeonRun.cpp, #140): the LFG dungeon id of a dungeon run, set when the Dungeon Finder took the group in (0: none)
uint32 DungeonRunDungeonId(uint32 runId);

class TC_GAME_API PartyBotMgr
{
public:
    static PartyBotMgr* instance();

    // returns an error text, empty on success
    std::string AddBot(Player* leader, std::string name);
    // name, "tank" / "healer" / "dps", a spec ("holy") or a class ("paladin"): a free bot of the leader's faction
    std::string AddBotByRole(Player* leader, std::string const& what);
    // a new bot character for this spec on the next free partybot account, on the creator's faction
    std::string CreateBot(Player* creator, uint32 specId, std::string& name);
    static ChrSpecializationEntry const* FindSpec(std::string const& className, std::string const& specName);
    std::string RemoveBot(Player* leader, std::string const& name);   // empty name = all of the leader's bots
    // .partybot questtest <class> [race] [max level]: a fresh level-1 quest-test bot (QuestBot.cpp), up to 4 at a time (one per race/class)
    std::string StartQuestTest(Player* gm, std::string text);
    uint32 StopQuestTests();            // .partybot questtest stop: any GM's run

    // ---- #140 A (PartyBot.cpp): bots at any level
    // a bot character of this spec at this level (10..110, not below the class's starting level) on a free partybot
    // account, faction by `alliance` (partybot_characters setup 2). Its first login keeps the level (the core teaches the
    // class and spec spells of that level at login), sets the spec, the talents of every unlocked row and level-scaling
    // heirlooms. Returns an error text, empty on success; guid = the new character.
    std::string CreateLevelBot(uint32 specId, uint8 level, bool alliance, std::string& name, ObjectGuid& guid);
    // after a bot's level-up (dungeon or quest test), out of combat: the talent row that just opened
    static void OnBotLevelUp(Player* bot);
    // ---- end #140 A
    // ---- C (DungeonRun.cpp, #140): .partybot dungeontest <dungeon id | name | random> [level]: five bots queue through the
    // Dungeon Finder and run dungeons until stopped; returns the text for the GM (the run, or why not)
    std::string StartDungeonTest(Player* gm, std::string text);
    uint32 StopDungeonTests();          // .partybot dungeontest stop: every run, its sessions dismissed
    std::vector<std::shared_ptr<PartyBotSession>> GetBots(ObjectGuid leaderGuid);
    uint8 CountBots(ObjectGuid leaderGuid);
    // rotation of a spec, in priority order (world.partybot_spells, loaded once)
    std::vector<PartyBotSpell> const* GetSpells(uint32 specId);

    static uint32 const MaxBotsPerLeader = 4;

private:
    void Cleanup();
    uint32 FreeBotAccount();            // a partybot account without characters; _lock held
    uint32 ReserveBotAccount();         // FreeBotAccount + mark it used, under _lock (0 = none)
    void ReleaseBotAccount(uint32 accountId);   // undo a reservation whose character was not created
    uint32 QuestTestCount();            // _lock held
    // ---- C (DungeonRun.cpp): a bot for a dungeon role (lfg::LfgRoles) at a level: an idle partybot character of that
    // level and faction whose spec is not in usedSpecs, else a new one (CreateLevelBot); and its session (dungeon mode).
    // Phase 3 (bots fill a queued player's missing roles) can reuse both
    std::string PickDungeonBot(uint8 role, uint8 level, bool alliance, std::set<uint32>& usedSpecs, ObjectGuid& guid, uint32& specId);
    std::shared_ptr<PartyBotSession> StartDungeonBot(ObjectGuid guid, ObjectGuid tankGuid, uint8 role);

    std::mutex _lock;
    std::vector<std::weak_ptr<PartyBotSession>> _bots;
    std::set<uint32> _usedAccounts;     // bot accounts given a character this run (the character save is asynchronous)
    std::once_flag _spellsLoaded;
    std::unordered_map<uint32, std::vector<PartyBotSpell>> _spells;
};

#define sPartyBotMgr PartyBotMgr::instance()

// QuestBot.cpp: the AI of a quest-test bot
PlayerAI* NewQuestBotAI(Player* bot, ObjectGuid gmGuid, uint8 maxLevel);

// ---- B (DungeonBotAI.cpp, #140): the tank's AI in a dungeon run. The four others keep PartyBotAI with the tank as leader.
PlayerAI* NewDungeonLeaderAI(Player* tank, uint32 runId);
// B: call from the tank's session update while the tank is dead (Player::Update runs no AI then): wipe handling,
// the tank back to the entrance and up (the members' sessions then resurrect them next to it)
void DungeonLeaderDeadUpdate(Player* tank, uint32 diff);
// C (DungeonRun.cpp): called by B when the run is over (all bosses dead, or given up); C logs out / requeues
void DungeonRunEnded(uint32 runId, bool cleared, std::string const& reason);

#endif
